### PR TITLE
Fix MoveI* when inner content is selected #4275

### PR DESCRIPTION
**Pull request by Xadoy**
**What this PR does / why we need it**:

Fixes a bug where MoveInsideCharacter does not work if the inner content is already selected. Although pull request #4280 tried to fix the same issue, in my opinion, it is a work around and it did not fix the root cause. In comparison, this pull request also covers the case that a user in visual mode and tries to select content in two layers of curly braces by hitting "v" followed by "i{" then "i{".

**Which issue(s) this PR fixes**
#4275 

**Special notes for your reviewer**:
Found another issue when I was tracking this issue, I will create a new issue soon.

### CODE REVIEW

**Comment by J-Fields** [comment]
@Xadoy Would you mind adding test cases?

**Comment by Xadoy** [comment]
> @Xadoy Would you mind adding test cases?

Of course, I will add the test cases. But in this case, #4280 has added some test cases, how should I process this. Sorry I am kinda new to open source contribution.

**Comment by J-Fields** [comment]
Feel free to borrow those test cases and add any that your fix covers that aren't already there

**Comment by Xadoy** [comment]
@J-Fields I borrowed and modified some test cases. In total, 32 new test cases are added. Let me know if you think this is too much. It covers all brackets, all cases with starting bracket or ending bracket. Also, multiple line scenarios are covered......

**Comment by J-Fields** [comment]
Thanks @Xadoy for adding tests and having patience with my sporadic open source schedule 🙂

**Comment by asinbow** [comment]
Super cool! Thanks!

**Pull request merged**
