### PR TITLE
feat: use winston for logging

### PR DESCRIPTION
**Pull request by jpoon**
**What this PR does / why we need it**:

1. Logging

* Aim of this PR is to make it easier to log messages to enable users to easier debug this extension
* Use WinstonJS for logging which takes care of a bunch of stuff we were manually handling in our logger. Logs will appear in `Help->Toggle Developer Tools`
* Create new configuration for adjusting extension debug settings. The only value in there right now is `loggingLevel`. Default configuration: 

```
debug: {
   loggingLevel: 'error'
}
```

* Created a new Winston Transport (https://github.com/jpoon/winston-console-for-electron) to enable logging to console for Electron apps

2. Configuration-Reloading

* Enable hot-reloading of remapping configurations

**Which issue(s) this PR fixes**

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by jpoon** [comment]
Any comments @VSCodeVim/maintainers before merge?

**Comment by xconverge** [comment]
Overall LGTM, still would be nice to try and split up cleanup with new features when possible but no worries

Winston looks cool and should be helpful!

**Comment by xconverge** [comment]
Is the verbose logging level used anywhere?

**Comment by jpoon** [comment]
@xconverge agreed on the split. sorry about that, i tend to get carried away.

> verbose

not yet. i've only just been using error/warn/debug.

**Pull request merged**
