### PR TITLE
Support `[ and `] commands to go to start / end of previously operated text

### PR DESCRIPTION
**Pull request by haifengkao**
same as https://github.com/VSCodeVim/Vim/pull/3672
but I have added the test cases

### CODE REVIEW

**Comment by haifengkao** [comment]
anyone want to merge it?

**Comment by haifengkao** [comment]
hello?

**Comment by joelrobichaud** [comment]
Hey, thanks for writing tests for this. I hope it gets merged soon!

**Comment by haifengkao** [comment]
@J-Fields Thanks I will add the support when I need it :(

**Pull request merged**
