### PR TITLE
Upgrade packages

### PR DESCRIPTION
**Pull request by jpoon**
* Upgrade npm packages. Add `package-lock.json` file
* Fix lint issues
* Clean-up unused build tasks
* Refactor task queue, it was bugging me

### CODE REVIEW

**Comment by xconverge** [comment]
Might want to add package-lock.json to the .gitignore?

**Comment by jpoon** [comment]
I am intending to commit `package-lock.json` (ie. I don't want it in the gitignore).

**Comment by xconverge** [comment]
Got it, just read up on https://yarnpkg.com/blog/2016/11/24/lockfiles-for-all/

**Comment by xconverge** [comment]
LGTM

**Pull request merged**
