### PR TITLE
Implement gn,gN command

### LINKED ISSUE #1955: FEATURE: `gn` text object support for matching the last search term
* Click *thumbs-up* 👍 on this issue if you want it!
* Click *confused* 😕 on this issue if not having it makes VSCodeVim unusable. 

The VSCodeVim team prioritizes issues based on reaction count. 

--------

**FEATURE REQUEST**

In Vim I loved the `gn` text object (not sure if it was exactly a text object. It would be matching always the last used search term. So for example you could search for `foo` with `/foo` and then change then next match of this search term with `cgn` or delete with `dgn`.

Now this gives you the possibility to jump and modify the next search match in one go. That comes especially handy when combined with `.` So for renaming `foo` to `bar` in a file you search for it with `/foo`, press `cgn` type the new name `bar` and repeat with `.`

So I request to include the `gn` text matching into the VSCodeVim as it is a very useful feature.

**RESOURCES**

Here is a blog post and a vimcast about the topic:
http://alexkuang.com/blog/2015/01/24/gn-in-vim/
http://vimcasts.org/episodes/operating-on-search-matches-using-gn/

### PR DESCRIPTION
**Pull request by tyru**
# What this PR does / why we need it

Vim's `gn` and `gN` command is so powerful.
It works in normal-mode, visual-mode, operator-pending-mode.
I implemented normal-mode and visual-mode.

~~But supporting operator-pending-mode seems a little bit difficult.~~
~~So this PR does not include it 😭~~
I made it to work in also operator-pending-mode! 😆 

# Which issue(s) this PR fixes

~~This PR does not fix, but related to #1955~~
Fixes #1955

### CODE REVIEW

**Comment by tyru** [comment]
The test file should conflict with #2588, I will fix when this or #2588 is merged.

**Comment by tyru** [comment]
> But supporting operator-pending-mode seems a little bit difficult.
> So this PR does not include it 😭

I made it to work in also operator-pending-mode!! 🎉 
This PR fixes also #1955.

**Comment by tyru** [comment]
oooops sorry, `test.only` is left in test codes...
Fixed and confirmed all tests are passed in CI, and rebased.

**Comment by tyru** [comment]
> I am going to do my best to continue to review your PRs and keep you unblocked...

Ah, don't mind.
I'm now on vacation so I have enough time to fix what I concerned about (until 5/6).
I'm using this extension at work and I can't live without this :)
Thanks for creating a great extension 😄

**Comment by xconverge** [comment]
Any chance we can also handle gN just so that we stay consistent?

**Comment by xconverge** [comment]
did you test cgn and dgn?

**Comment by tyru** [comment]
@xconverge Okay, I will implement gN, and add tests for cgn and dgn :)

**Comment by tyru** [comment]
@xconverge implemented gN, and added tests :)

**Comment by xconverge** [comment]
Thank you so much for your contributions! This next release is all you!

**Pull request merged**
