### PR TITLE
Fix to allow A while in visual mode

### PR DESCRIPTION
**Pull request by xconverge**
Yay! We love PRs! 🎊

Please include a description of your change and ensure:

- [X] Commit message has a short title & issue references
- [X] Each commit does a logical chunk of work.
- [X] It builds and tests pass (e.g `gulp`)

More info can be found on our [contribution guide](https://github.com/VSCodeVim/Vim/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by johnfn** [comment]
This is the Visual Block Mode A. You want the Insert Mode A, right?

**Comment by xconverge** [comment]
@johnfn no idea what I was doing here, really don't

Same as the other one though, I can find any regressions but can't say I am fluent enough with the commands to know exactly how they could work on all of the edge cases

**Comment by johnfn** [comment]
Been thinking about this more and I think it's okay. Could you just remove the line 

`mustBeFirstKey = false;`

entirely (as `mustBeFirstKey` defaults to `false` so there's no reason to set it). 

Same thing with your other PR.

**Comment by johnfn** [comment]
Thanks, @xconverge!

**Pull request merged**
