### PR TITLE
Bugfix: search backwards with operator

### LINKED ISSUE #4506: Delete backwards (d?) action is not working
In vim you can do `d?word` to delete backwards in a file until `word` is found.

VSCode Vim doesn't seem to support it. 

Running latest version of VS Code and the plugin.

### LINKED ISSUE #4647: c?search_term<Enter> does not produce expected result.
**Describe the bug**
In normal mode:
`c?{searchterm}<Enter>` does not produce expected result from Vim (VIM - Vi IMproved 8.0 on Ubuntu and Gvim on Windows)

**Expected behavior**
`c?{searchterm}<Enter>` should delete backwards from cursor until (inclusive) first char of the term found and go in insert mode. Stay in normal mode if no term is found.

- Extension (VsCodeVim) version: 1.13.0
- VSCode version: 
Version: 1.43.0 (system setup)
Commit: 78a4c91400152c0f27ba4d363eb56d2835f9903a
Date: 2020-03-09T19:47:57.235Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.17763

- OS: Windows [Version 10.0.17763.1098]

Extension | Author (truncated) | Version
-- | -- | --
dart-code | Dar | 3.8.1
flutter | Dar | 3.8.1
vscode-markdownlint | Dav | 0.34.0
gitlens | eam | 10.2.1
vscode-html-css | ecm | 0.2.3
vscode-JS-CSS-HTML-formatter | lon | 0.2.3
python | ms- | 2020.2.64397
remote-wsl | ms- | 0.42.3
cpptools | ms- | 0.26.3
Go | ms- | 0.13.1
ascii-plist | spe | 1.0.3
vim | vsc | 1.13.0

### PR DESCRIPTION
**Pull request by sql-koala**
**What this PR does / why we need it**:
This PR removes an unnecessary restriction that prevents search backwards ("?") with an operator.
First build fails on new test.

**Which issue(s) this PR fixes**
Fixes #4506
Fixes #4647

**Special notes for your reviewer**:
This condition prevents "?" after an operator.
`&& vimState.recordedState.operator === undefined`
But it is not needed because `doesActionApply` is smart enough to figure out, that "?" after "g" should not trigger the search command (you can also type "cg?" without messing vim up).  (I did capture and log the result of super() ).
So we can remove the condition. But then we can remove the whole method because it is just default inherited code.

### CODE REVIEW

**Comment by sql-koala** [comment]
Finally, you cant do test driven development  better :|

**Comment by sql-koala** [comment]
Must have banged my head against the wall many times, :exploding_head:  but it worked out

**Comment by J-Fields** [comment]
🙂 Feel free to submit an issue about your test situation - it's much nicer when you can run them locally

**Comment by berknam** [comment]
Have you tried using docker for tests? All you have to do is install docker and then run `npx gulp` (builds and run tests) you can even run just some test suites with regex like this `npx gulp --grep "Mode.Normal"`.

**Comment by sql-koala** [comment]
@J-Fields , @berknam 
Thanks for offering help. I am on win7, so I cant run docker.
But that's more of a "just my problem" situation. I found that I can do this in launch.json to run my new tests from vscode. That's good enough.
```
      "env": {
        "MOCHA_GREP": "sqlkoala"
      },
```

**Pull request merged**
