### PR TITLE
fixes #739

### LINKED ISSUE #739: cw doesn't work on empty line
### What did you do?

```js
if (true)
|// Nothing other than newline here
}
```

Press `cw`

### What did you expect to happen?

```js
if (true) {
|// Nothing other than newline here
}
```

in insert mode.

### What happened instead?

```js
if (true) {

}|
```

In insert mode.

### Technical details:

* VSCode Version: 1.5.0
* VsCodeVim Version: 0.1.10
* OS: OS X 10.11.6

### PR DESCRIPTION
**Pull request by xconverge**
Weird bug, weird fix, but I am ok with it if you are

Yay! We love PRs! 🎊

Please include a description of your change & check your PR against this list, thanks:

- [X] Commit message has a short title & issue references
- [X] Each commit does a logical chunk of work.  
- [X] It builds and tests pass (e.g `gulp tslint`)

More info can be found by clicking the "guidelines for contributing" link above.

### CODE REVIEW

**Comment by johnfn** [comment]
How does this handle, say, `c}` in the same situation?

I think this may be a special case on `w`, not `c`.

**Comment by xconverge** [comment]
hah ok so you are right, I fixed this on w, however c} does not work right (and did not before so I will fix that as well since you brought it up)

**Comment by rebornix** [comment]
Just one comment and you may also want to write a simple test to cover this scenario.

**Comment by johnfn** [comment]
I don't understand why this behavior would happen for `cw` but not `dw`. I see two possibilities:

1. We have another special case handling thing in `d`. If so, they should both be moved into `w`. 
2. Something very strange and worrying is going on. If so, figure out the source of the strangeness and worrisomeness.

**Comment by xconverge** [comment]
@johnfn what is the special case I have in "c" now?

**Comment by johnfn** [comment]
My bad, @xconverge. I misread your PR. (And also I completely missed your reply. I have trouble with Github's notification system...) It looks good to me. If you bring it up to date, I'll merge it! :)

**Pull request merged**
