### PR TITLE
[WIP] Fixes #1992 Batch replay text insertion for dot command

### LINKED ISSUE #1992: Repeating typing with `.` is extremely slow.
* Click *thumbs-up* 👍 on this issue if you want it!
* Click *confused* 😕 on this issue if not having it makes VSCodeVim unusable. 

The VSCodeVim team prioritizes issues based on reaction count. 

--------

**What happened**:

Typing a bunch of stuff, exiting insert mode, perform a motion, then press `.` to repeat typing. The previously typed characters will be inserted one at a time. If you typed a whole word or two, it can take up to a second to repeat the typing action.

**What did you expect to happen**: 

It should instantaneously insert all of the typed characters in one go.

**How to reproduce it**:

1. Open a new file and insert several blank lines.
2. Go to the first blank line, type `i` to enter insert mode, and type random giberish on that line.
3. Press `esc` to exit insert mode.
4. Press `j` to go to the next line.
5. Press `.` to repeat the typing from step 2.

Notice how long it takes for the gibberish insert to be reproduced.

You may repeat steps 4 and 5 for as many blank lines as you have to experience the issue again.

Depending on timing factors, you may also notice that about halfway through the insertion, the auto-completion dropdown momentarily appears, indicating that this assert is not being performed atomically.

### PR DESCRIPTION
**Pull request by xconverge**
Need to do some more testing on here, I think it is the right idea but need to make sure it doesn't break anything.

Regular use shows it is nearly instantaneous, but I am worried I am breaking some other content change replay besides text insertion

### CODE REVIEW

**Comment by xconverge** [comment]
Also need to handle the case of autocomplete counting as a content change that overlaps other content changes. Basically I need to loop through all content changes, batch together the ones the overlap and push individual chunk inserts for each batch

**Comment by Chillee** [comment]
Awesome!

**Comment by xconverge** [comment]
Arg this is a lot harder than it seems.

We already do batching/look for overlapping transforms with the insertText transform, the problem is we tend to use insertTextVSCode which allows vscode to add closing parenthesis etc.

I might need to give up for a bit on this, will think about it some more..

**Comment by xconverge** [comment]
Closing this for now

**Pull request closed without merging**
