### PR TITLE
Substitute, use transformations

### LINKED ISSUE #4915: Substitution doesn't operate on whole block if newlines are inserted
**Describe the bug**
If I use `s/.../... \n .../` on a highlighted blocks, only half of the lines are changed. (suspicion - it iterates on original line range, without accounting for additions)

**To Reproduce**

1. Create a file with:
```
a: b
c: d
e: f
g: h
```
2. Highlight all lines (`ggVG`)
3. Run replacement (`:s/: /\n- /`)

**Expected behavior**
```
a
- b
c
- d
e
- f
g
- h
```
instead of current:
```
a
- b
c
- d
e: f
g: h
```

**Environment (please complete the following information):**

- Extension (VsCodeVim) version: 1.14.5
- VSCode version: 1.45.1
- OS: macos mojave

### PR DESCRIPTION
**Pull request by sql-koala**
**What this PR does / why we need it**:
this refactors substitute `:s` and replaces deprecated methods to access the document.

**Which issue(s) this PR fixes**
fixes #4915
relates to #5663 

**Special notes for your reviewer**:
the diff for tests is quiet large and ugly, because many tests need to be adapted. I provide the commit for tests first, with a CI run,
https://github.com/VSCodeVim/Vim/runs/2254892205 
 so you can see that only a few tests are changed a bit. For some tests, we need to adapt expected cursor position to be the BOL, which is also what gvim does.

### CODE REVIEW

**Comment by sql-koala** [comment]
@J-Fields can you look at the one failing test?  `1) : (command) register can be used as a macro` 
I have no clue why this does not work or how this could be connected to the change.

**Comment by sql-koala** [comment]
well, gnaarf :| ... two things
1. when using interactive / confirm `:s` with a transformation, the document is not updated right away, only after last confirmation.
2. executing the : register `@:` does not work after using transformation

what to do?

**Comment by J-Fields** [comment]
Thanks a bunch @sql-koala! I just pushed a change which should fix that test - the issue was that macros are replayed via a `'macro'` transformation, and transformations created in that process weren't responded to. My fix seems like a band-aid on larger architectural issues, but it should do the trick for now.

**Comment by J-Fields** [comment]
> when using interactive / confirm `:s` with a transformation, the document is not updated right away, only after last confirmation.

I don't care enough about this to prevent merging - I've created #6427 to track it

**Comment by sql-koala** [comment]
yay, merged. thanks for the help @J-Fields

**Pull request merged**
