### PR TITLE
#1938 - Surround: keep attributes when changing tags

### PR DESCRIPTION
**Pull request by ToucheSir**
As per https://stackoverflow.com/questions/16340037/change-html-tag-in-vim-but-keeping-the-attributes-surround/31098722#31098722 and https://github.com/tpope/vim-surround/pull/131, it should now be possible to keep attributes with `cst<tag` + `<CR>` or `cstt` + `tag` + `<CR>`.

### CODE REVIEW

**Comment by Chillee** [comment]
@ToucheSir Could you write a test covering this new functionality?

**Comment by xconverge** [comment]
Just 1 or 2 test cases in:

https://github.com/VSCodeVim/Vim/blob/master/test/plugins/surround.test.ts

please! Thanks!

**Comment by ToucheSir** [comment]
Apologies for not getting to this sooner! I created a couple of test cases locally for the new functionality, but they seem to fail based on some unrelated discrepancy between vim-surround and vscodevim surround. Will look into crafting a robust test cases (and also trying to identify the difference in surround behaviour) this weekend!

**Comment by xconverge** [comment]
what does the test case look like that would fail? Just curious what the differences are between surround-vim and our implementation, can just add the test case you tried as a comment on this PR

**Comment by ToucheSir** [comment]
Ah, apologies for letting this lapse again. I got a chance to run some simple examples (VSCode 1.17.2, VScodeVim 0.10.2).

Given a new file (with or without the html syntax activated) and the snippet `<h2>test</h2>`:

| Start | Input | Result (vim-surround) | Result (VSCodeVim-surround) |
|-|-|-|-|
| `█<h2>test</h2>` | `csttdiv>` | `█<div>test</div>` | `<div█>test</div>` |
| `<h█2>test</h2>` | `csttdiv>` | `█<div>test</div>` | `<div>te█st</div>` |
| `<h2>te█st</h2>` | `csttdiv>` | `█<div>test</div>` | `<div>te█st</div>` |
| `<h2>test<█/h2>` | `csttdiv>` | `█<div>test</div>` | `<div>test</di█v>` |
| `<h2>test</h█2>` | `csttdiv>` | `█<div>test</div>` | `<div>test</d█iv>` |
| `<h2>test</h2█>` | `csttdiv>` | `█<div>test</div>` | `<div>test</█div>` |

It would seem that vim-surround always "snaps" the cursor back to the beginning of the tag. In VSCode, the ending cursor position seems to depend somewhat on the beginning position. I've also found in some more informal usage that the length of tag names and internal text may also affect ending cursor placement, but have yet to definitively test that observation. 

Stranger things happen if the above html snippet is the first line in the file (results that are the same as above omitted for brevity):

| Start | Input | Result (vim-surround) | Result (VSCodeVim-surround) |
|-|-|-|-|
| `<█h2>test</h2>` | `csttdiv>` | `█<div>test</div>` | `<<div█>test</div>` |
| `<h█2>test</h2>` | `csttdiv>` | `█<div>test</div>` | `<h<d█iv>test</div>` |
| `<h2>te█st</h2>` | `csttdiv>` | `█<div>test</div>` | `<h2>te█st</h2>`  (no change for inner text)|
| `<h2>test█</h2>` | `csttdiv>` | `█<div>test</div>` | `<h2>█/div>/h2>` |
| `<h2>test</█h2>` | `csttdiv>` | `█<div>test</div>` | `<h2>iv█>/<2>` |
| `<h2>test</h2█>` | `csttdiv>` | `█<div>test</div>` | `<h2>█>/h2<` |

I'm not sure that the vim-surround behaviour of always moving the cursor back to the beginning of the opening tag is always the desired behaviour, but thus far it's not entirely clear what is causing the inconsistent behaviour in VSCode.

I hope this can be of some help! Hopefully whatever resolution is found for this will also work for the retained attributes case.

**Comment by xconverge** [comment]
Ok on that note then, can you just add 1 test that covers the basics, and has our implementation of the cursor, you can put a comment next to the test if you want saying why it is different so that IF someone wants to change OUR implementation, that test will fail and they will see there is a comment on the test and that they just need to update the test

Then we can merge this, the functionality makes sense to me and the cursor position is out of scope for this ticket

**Comment by jpoon** [comment]
Closing due to lack of activity. Please address the review comments and re-open when you are ready for review/merge.

**Pull request closed without merging**
