### PR TITLE
Remove old workaround that is no longer needed

### LINKED ISSUE #1962: Multi-cursor append line above (Shift+O) only works for 1 cursor
* Click *thumbs-up* 👍 on this issue if you want it!
* Click *confused* 😕 on this issue if not having it makes VSCodeVim unusable. 

The VSCodeVim team prioritizes issues based on reaction count. 

--------

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

**Environment**:

- **VSCode Version**: 1.14.2
- **VsCodeVim Version**: 0.9.0
- **OS**: Windows 10

**What happened**:

1) be in normal mode
2) using Alt+leftclick, create cursors at multiple lines
3) press Shift+O
4) a new line is appended only above the first cursor

**What did you expect to happen**: 

4) new lines are appended above all cursors

(**note:** it already works correctly when appending below with O instead of above with Shift+O)

**How to reproduce it**:

see What happened

### PR DESCRIPTION
**Pull request by cvaldev**
**What this PR does / why we need it**:
The issue this workaround used to solve appears to have been fixed in the upstream and is no longer reproducible. Additionally, because it would update the `activeTextEditor.selection` it caused vscode to loose our selections in multicursor mode, thus `editor.action.insertLineBefore` would only insert a line above the first cursor and subsequently take us out of multicursor mode.

**Which issue(s) this PR fixes**
fixes #1962 

**Special notes for your reviewer**:
A bit unrelated but I'm unsure if I should open an issue for this, I normally do format on save but since prettier was added it re-formats the whole document and would have made this PR a mess. Should I push another commit with the prettier formatting?

### CODE REVIEW

**Comment by J-Fields** [comment]
> A bit unrelated but I'm unsure if I should open an issue for this, I normally do format on save but since prettier was added it re-formats the whole document and would have made this PR a mess. Should I push another commit with the prettier formatting?

Is it the line endings that are being changed?

**Comment by cvaldev** [comment]
@J-Fields Sorry I didn't look at what it was doing initially, there are no changes to line endings as far as I can tell but it's removing all the trailing commas.

**Comment by J-Fields** [comment]
Ah! `npm install` should resolve that, I think. The default for `trailingComma` changed from `none` to `es5` in prettier 2.0, so I removed it from our `.prettierrc` (we had it set to `es5` before)

**Comment by cvaldev** [comment]
> Ah! `npm install` should resolve that, I think. 

Thanks! that did it.

**Pull request merged**
