### PR TITLE
Add new logo icon

### PR DESCRIPTION
**Pull request by kevincoleman**
New logo icon file
Updated banner color to match logo
logo source design files in `design/`

### CODE REVIEW

**Comment by xconverge** [comment]
This is awesome, thanks @kevincoleman

**Comment by jpoon** [comment]
Mind actually putting it all under /images?

**Comment by jpoon** [comment]
@kevincoleman are the edges of the icon also #208ecd? As we're changing the banner color to #208ecd on https://marketplace.visualstudio.com/items?itemName=vscodevim.vim, want to make sure that they don't bleed into the icon.

**Comment by kevincoleman** [comment]
@jpoon Ahhh. Good point. The edges are the also #208ecd, so that won’t work too well.

Options:
add a white border or background around the icon design to give it somewhat of a “sticker” feel.
pick another banner color so as to avoid the bleed issue.
any other ideas?

**Comment by jpoon** [comment]
Let's go with the easy one -- different banner color.

**Comment by jpoon** [comment]
Sweeet. Thanks @kevincoleman .

**Pull request merged**
