### PR TITLE
Add support for za Vim binding

### PR DESCRIPTION
**Pull request by aquova**
**What this PR does / why we need it**:
Adds support for the Vim 'za' keybinding, which toggles a fold.

**Which issue(s) this PR fixes**
#1453 

**Special notes for your reviewer**:
This simply binds the new VSCode editor.toggleFold option to the 'za' combination. I was unable to find a way to implement specifying a number modifier, as you need to know whether or not to travel up or down.

### CODE REVIEW

**Comment by xconverge** [comment]
@RegisterAction
class CommandToggleFold extends CommandFold {
  keys = ['z', 'a'];
  commandName = 'editor.toggleFold';
  public async exec(position: Position, vimState: VimState): Promise<VimState> {
    await vscode.commands.executeCommand(this.commandName);
    vimState.cursors = await getCursorsAfterSync();
    await vimState.setCurrentMode(ModeName.Normal);
    return vimState;
  }
}

This seems to work better for me? are you using the foldFix configuration option?

**Comment by xconverge** [comment]
Without the getCursors sync and foldFix when I toggle it closed it reopens right away unless you are perfectly on the start of the fold (ie. not within the folded region"

**Comment by aquova** [comment]
Yes, it seems you're right. When foldFix is disabled, I'm seeing it reopen unless you're directly on the start of the fold.

**Comment by xconverge** [comment]
Looks good and when I tested it it seems to work fine-ish, except for the whole foldFix concept but thats another ticket!

**Pull request merged**
