### PR TITLE
Implement tag movements

### LINKED ISSUE #588: Tag Deletes
I'm trying to delete text in a HTML tag by pushing `DIT`, but this feature is not available.  Will this feature be available in future milestones?

### PR DESCRIPTION
**Pull request by sectioneight**
Fixes #588, #567

### CODE REVIEW

**Comment by sectioneight** [comment]
Hmmm, tests passed on Linux for Travis, appear to have timed out on OS X?

**Comment by sectioneight** [comment]
Ok, I think this is ready for review now. I'm not a heavy tag user, but I'm pretty sure I got the semantics right. Tested manually on one of my projects.

**Comment by rebornix** [comment]
@sectioneight this is insanely awesome, I just figured out that you implemented most text object motions in https://github.com/VSCodeVim/Vim/blob/master/ROADMAP.md#text-objects-only-in-visual-mode-or-after-an-operator. `ab`, `ib`, etc are just synonyms of `a[`, `i[`, etc. After this PR gets merged, the only text object motions left on the roadmap are `ap` and `ip`.

**Comment by sectioneight** [comment]
Thanks @rebornix :) I am just **so** happy with how much more enjoyable vscode and this plugin have made my editing life recently, it's the least I can do.

**Comment by sectioneight** [comment]
Tests passed on linux, seems like one of them is flaky on OS X?

**Comment by sectioneight** [comment]
Actually, the test failing on travis is also failing on master (and my branch) on my laptop:

```
  506 passing (2m)

  1 failing


  1) Dot Operator Can repeat actions that require selections:

      Cursor CHARACTER position is wrong.
      + expected - actual

      -4
      +8

      at Suite.suite (test/mode/normalModeTests/dot.test.ts:56:5)
```

**Comment by sectioneight** [comment]
Ok, a rebase/retrigger seems to have fixed the tests

**Comment by johnfn** [comment]
Really nice work, as usual. :) Thanks, @sectioneight!

**Comment by kidproquo** [comment]
Sorry, I must be dense. How does this work? I tried `dit` and `cit` in Normal mode. Nothing happens.

**Comment by xconverge** [comment]
@kidproquo can you post the text line you tried to use dit and cit on?

**Comment by xconverge** [comment]
for example:

<test>aaa|aaa</test>

then dit or cit gives me

<test>|</test>

**Comment by kidproquo** [comment]
Aha, now I get it. This only works in single-lines. Doesn't work in this scenario:


```
<test>

        aaa|aaa

</test>
```
Should I submit a bug?

**Comment by xconverge** [comment]
Sure that would be a good bug to file, thanks!

**Pull request merged**
