### PR TITLE
Remove "vim.remap" from the command palette

### LINKED ISSUE #5841: Cannot read property 'after' of undefined
**To Reproduce**

I'm running VSCode Insiders on Mac:

```
Version: 1.52.0-insider
Commit: 532ba43c78c82b24bdf94f9edde30cdf9b9bfa12
Date: 2020-12-05T01:08:42.214Z
Electron: 9.3.5
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Darwin x64 19.6.0
```

1.  Run the action "Vim: Remap key combination  that VS Code supports as Vim ..." (vim.remap)
  - I did this because of my request for the feature for #5822 where it was said that C-f and C-b should be working as page up/down - but I'm not seeing that. I then tried to do this remap, and saw the error - I'm wondering if that is related then.
2.  See error

**VSCodeVim version**: 1.18.0

<details><summary>Stack trace</summary>

```
TypeError: Cannot read property 'after' of undefined
    at Object.promise (/Users/darrenk/.vscode-insiders/extensions/vscodevim.vim-1.18.0/out/extension.js:9:229185)
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
    at Object.runTasks (/Users/darrenk/.vscode-insiders/extensions/vscodevim.vim-1.18.0/out/extension.js:11:285853)
```

</details>

### PR DESCRIPTION
**Pull request by berknam**
**What this PR does / why we need it**:
Remove "vim.remap" from the command palette
- This command is supposed to be used in keybindings, it can't be used
directly from the command palette

**Which issue(s) this PR fixes**
- fixes #5841

**Special notes for your reviewer**:
We should add an entry for this command explaining its use on the README file. I just don't know were or if we should even do it at all. I'm afraid it might create more confusion and future issues.

We really need a Wiki! 😄 Then we could add an advanced section inside a Remappings section where we could add this.

I also think this might be the cause of the issues related to #5306. But I'm not sure because no one as yet explained what they were doing...

### CODE REVIEW

**Comment by J-Fields** [comment]
Hmm, I wasn't aware that you could provide and execute commands that aren't exposed in `contributes.commands`, but looks like that's fine.

I wonder if anyone even uses this - I was only vaguely aware of it. Is the point to allow incorporating `when` clauses to make remaps conditional on context?

**Comment by J-Fields** [comment]
> We really need a Wiki! 😄

Agreed 100%. I'd like to break the README up and migrate the pieces to the wiki along with more detailed info. Just haven't found the time yet.

**Comment by J-Fields** [comment]
In addition to this, we should check the existence/structure of the argument to `vim.remap` and throw a more helpful error

**Comment by berknam** [comment]
> 
> 
> Hmm, I wasn't aware that you could provide and execute commands that aren't exposed in `contributes.commands`, but looks like that's fine.

Me neither. Just found out now as well.

> I wonder if anyone even uses this - I was only vaguely aware of it. Is the point to allow incorporating `when` clauses to make remaps conditional on context?

That is one possibility yes, but I think the main advantage of "vim.remap" is that it allows to remap keys that are not captured by Vim. Like mentioned here https://github.com/VSCodeVim/Vim/issues/5186#issuecomment-699168965, this allows to map keys from different keyboard layouts that are not captured by Vim.

**Comment by berknam** [comment]
There is also the issue that currently if you have some `after` and `commands` as well, then `commands` will never run, because "vim.remap" checks for `after` and then returns, only if it `after` is undefined will it look for commands. This is not the same behavior as it happens in our remaps.

**Comment by berknam** [comment]
@J-Fields Does this last commit make it any better, at least for now?

**Pull request merged**
