### PR TITLE
Fixed "d" and "D" in multicursor mode

### PR DESCRIPTION
**Pull request by Platzer**
In Multi-Cursor mode "d" in Visual Mode and "D" in Normal-Mode is not working.
Added the current multicursorindex to the `Register.Put` method.

### CODE REVIEW

**Comment by Platzer** [comment]
I don't get it why that one is failing with my commit:
grafik
On my local machine it is working, i don't think is related to my changes but i cannot figure out why it is not working.

**Comment by xconverge** [comment]
@Platzer same problem on my PR as well

**Comment by jpoon** [comment]
Can you add tests around this? Thanks.

**Comment by johnfn** [comment]
Yeah, my bad for not getting to this earlier. The failing test concerns me. If you can figure that one out (and yeah add another test maybe?) this should be good to go.

**Comment by johnfn** [comment]
I'm actually not sure if this was necessary; I think the bug ended up being somewhere else. Can you check what's currently on master and see if this change is required?

**Comment by Platzer** [comment]
@johnfn, the deleting part is fixed in current release but putting into multi cursor register is still broken! would be fixed with this PR. I will try to have a look this week!

**Comment by Platzer** [comment]
@johnfn, travis is failing cause some npm stuff, but tests are okay.

**Comment by johnfn** [comment]
Sorry for taking so long on this, @Platzer. I've merged it in now.

**Pull request merged**
