### PR TITLE
Fix Bug #613 in command line writequit

### PR DESCRIPTION
**Pull request by Platzer**
Simple Bug fix for #613 ":wq command does not work"

### CODE REVIEW

**Comment by jpoon** [comment]
It looks like this will work. Can you also add tests?

**Comment by rebornix** [comment]
@Platzer do you mind squash the commits to a few meaningful ones as there are several `merge` commits. Besides, you may fall in love with `git rebase` :)

**Comment by Platzer** [comment]
Only two (4f000ad, b5e4dca) are relevant, the others must be from [fork syncing](https://help.github.com/articles/syncing-a-fork/). It's my second PR ever so whats the way to avoid these commits?

**Comment by Platzer** [comment]
I'm going to create a new PR to get rid of the "sync commits". I will try to add tests too.

**Comment by jpoon** [comment]
@Platzer as you're doing this on your fork, you can do a `git push --force` and the PR will automatically update.

**Pull request closed without merging**
