### PR TITLE
fixes #1084

### LINKED ISSUE #1084: Bracket pairs don't get deleted when you delete the first bracket
### What did you do?
https://gyazo.com/f6e305ea0d7afce408329e6ebf72402d
This happens for character pairs like [], {}, '', etc.

### What did you expect to happen?
Both characters in the pair to deleted.

### What happened instead?
Only one character was deleted.

### Technical details:

* VSCode Version: 1.7.2
* VsCodeVim Version: 0.4.3
* OS: Windows

### PR DESCRIPTION
**Pull request by xconverge**
Any thoughts on this? Seems like a positive effect?

When you enter a quote or parenthesis, vscode has an option to auto add the closing portion.

With this, when you remove the opening char, and the closing char is the immediate next character, it will remove the closing char as well.

### CODE REVIEW

**Comment by xconverge** [comment]
I am also considering putting an if statement around this to only do this if editor.autoClosingBrackets is set to true (which is default currently)

**Comment by johnfn** [comment]
Ideally we could delegate the work of deleting back to VSCode who would do the correct thing. Who knows what other auto-pairing characters they will add? 

If there's no easy way to do that, then this solution could work.

**Comment by xconverge** [comment]
Was my first thought as well, however since we had some matchers already I figured this was a possible solution. I am not sure what that call to delegate back to vscode would look like

**Comment by johnfn** [comment]
I think the matcher stuff is for the da" actions and stuff like that? I actually have no idea what it would look like either lol.

**Comment by xconverge** [comment]
Yea but the matchers have useful maps already of these paired characters, so as long as those stay updated this should work no problem

**Comment by xconverge** [comment]
Interesting, here is a call in vscode, so you are right, really this should be delegated. There should be a way in the api to call delete 1 char left and have this invoked

public static deleteLeft(config: CursorConfiguration, model: ICursorSimpleModel, cursor: SingleCursorState): EditOperationResult {
		let r = this.autoClosingPairDelete(config, model, cursor);

**Comment by rebornix** [comment]
@xconverge we have deleteLeft, deleteRight, deleteAllLeft and deleteAllRight in Code. The only catch with the first two is that they might not work perfectly in multi cursor mode (technical debt, I'm working on improving all commands that were implemented before we had multi cursor mode).

**Comment by xconverge** [comment]
Yea and then there is no way for me to use them right?

**Comment by johnfn** [comment]
Yah, the problem is that we need to know the position of where the cursor is going to be for multi cursor mode, and that's not provided by the moveRight/Left functions afaik.

**Pull request closed without merging**
