### PR TITLE
Created tests for modeInsert

### PR DESCRIPTION
**Pull request by benjaminRomano**

### CODE REVIEW

**Comment by jpoon** [comment]
please squash these commits: `git rebase -i HEAD~4`

**Comment by benjaminRomano** [comment]
@jpoon 

I typed that and I got this:
image

What do I do here? Sorry for the noob question. I've never squashed commits before :smile:

**Comment by jpoon** [comment]
No worries. https://davidwalsh.name/squash-commits-git

**Comment by benjaminRomano** [comment]
@jpoon I squashed the changes. Everything should be good to go.

**Pull request merged**
