### PR TITLE
update internal cursor position per Code selection change

### PR DESCRIPTION
**Pull request by rebornix**
Yay! We love PRs! 🎊

Please include a description of your change and ensure:

- [x] Commit message has a short title & issue references
- [x] Each commit does a logical chunk of work.
- [x] It builds and tests pass (e.g `gulp`)

More info can be found on our [contribution guide](https://github.com/VSCodeVim/Vim/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by xconverge** [comment]
Does this fix a problem and then create all of the original problems that we closed before we made this change? It makes sense to me, but I imagine some of the issues closed from the other day will reopen.

**Comment by rebornix** [comment]
let me give them a quick check.

**Comment by rebornix** [comment]
Verified  #872 #877 #882 #892 #895 #896, they are still good.

Verified #856, which we claimed it was fixed while actually it was still half broken without this PR.

#901 I'm not sure if I'm doing the right keystrokes, on both Master and my PR, it still doesn't work.

**Comment by xconverge** [comment]
LGTM then, thanks for checking those

What portion of the code was causing #882 then...

**Comment by johnfn** [comment]
@xconverge I _think_ the problem was that it would always go into that complex selection logic and eventually trigger `updateView`. Now that happens much more rarely. 

So I think we're good here.

**Pull request merged**
