### PR TITLE
Basic e motion

### PR DESCRIPTION
**Pull request by pottereric**

### CODE REVIEW

**Comment by jpoon** [comment]
I'm not entirely sure what you are trying to do. But to squash commits: https://github.com/ginatrapani/todo.txt-android/wiki/Squash-All-Commits-Related-to-a-Single-Issue-into-a-Single-Commit

**Comment by jpoon** [comment]
Again, I'd like to merge this but please squash the commits first. 

Re: #103

**Comment by pottereric** [comment]
Sorry, I didn't have time to get to this over the holidays. It looks like
someone else has implemented it now. So it doesn't matter anyway.

**Comment by jpoon** [comment]
No worries. Happy Holidays :tada: 

I'll close this in favor of https://github.com/VSCodeVim/Vim/pull/109

**Pull request closed without merging**
