### PR TITLE
fix - cursor position whenever changing editors - closes #2688

### LINKED ISSUE #2688: Wrong cursor position after using same file in two panels
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

It's a bug report

**What happened**:

1. Open same file in two panels (i.e. side by side) with vim mode enabled
2. At one buffer (A) jump to line 10
3. At second buffer (B) click at line 20
4. Get back to buffer A (at this point we are at line 10) and hit `j` (for vim "down by line" move)
5. I am taken to line 21

**What did you expect to happen**:

At point 5 I should be taken to line 11.

**How to reproduce it (as minimally and precisely as possible)**:

I've described it at the *What happened* section. Here is a [video](https://youtu.be/thmgfcGq6ro).

[video](https://www.youtube.com/watch?v=thmgfcGq6ro)

**Environment**:

- Extension (VsCodeVim) version: 0.12.0
- VSCode version: 1.23.1
- OS version: 10.13.2 (17C88)

**Update**

Seems like reverting [one change](https://github.com/VSCodeVim/Vim/commit/1c81cf3e657320a015e911ceee3fd07b0a6dda4c) helped. I've created a [PR](https://github.com/VSCodeVim/Vim/pull/2721).

For v0.14+ fix please see [the comment](https://github.com/VSCodeVim/Vim/issues/2688#issuecomment-401272852)

### PR DESCRIPTION
**Pull request by captaincaius**
**What this PR does / why we need it**:
Updates vimState whenever the active editor changes so that changing splits doesn't have you making edits to the wrong line

**Which issue(s) this PR fixes**
#2688 

**Special notes for your reviewer**:

I hand-tested it, and it seems to solve the problem, and undo seems to work properly too.  But there's some questions:

1. I see some branches in the selection change handler for "easymotion" ... TBH I have no idea what that is, so I'm not sure this patch will do "the right thing" in situations involving it.
2. ~~Likewise with the jump tracker.~~ thanks to @shawnaxsom 's teaching me how this works, it looks like the jump tracker is A-Okay.
3. Is this testable at all?  I grepped for ":sp" in test/ and got no results :(.
4. Are there any potential race conditions introduced by changing vimState.editor right in the event handler (outside the task queue)?  I put it there because the selection handler checks it outside the queue, so putting it inside would very likely introduce a race condition.
5. Disclaimer - I have zero experience with the VSCode API and the timing of its events - so review this as though a child in a playground wrote it (a child that <3s vscodevim :P).  I ran tests twice and they don't seem to flake, but I'm sure you folks have a lot more experience with any gotchas in their APIs, especially with regard to timing, synchronization, promise resolution, etc.

### CODE REVIEW

**Comment by xconverge** [comment]
Did you look at onDidChangeActiveTextEditor in extension.ts? Could this have been handled there or in updateView? I am just hesitant because you may have noticed the big comment above the function you changed

Regarding easymotion, https://github.com/VSCodeVim/Vim#vim-easymotion

**Comment by captaincaius** [comment]
Thanks for taking the time to review!

Dang, I did a search only in src/ for onDidChangeActiveTextEditor, so I didn't see it.  Thanks!  I agree that they should be combined.

I'm assuming it was in extension.ts for a good reason, so I'll augment the original handler instead and maybe make the handleActiveEditorChange call there.

Yup I noticed the big comment, and also how delicately the function seemed to be written, so I didn't want to change it from the point of view of the selection change event.

The selection change event isn't fired on a text editor change (even on a mouse click), so I broke down its input from the event into its constituents so that it could be used by both event handlers.

I'll give this some more careful thought and give it another stab later today when I have open-source-time :).

**Comment by captaincaius** [comment]
@xconverge thanks for the point in the right direction!  You were right - we can avoid touching even the interface of that function, because most of what's being done this way was previously being done in the existing handler, besides a little bug introduced in the undo fixes :).

I'm gonna close this and open a new PR to keep the commit log clean.

Thanks again! :)

**Comment by flowchartsman** [comment]
@captaincaius looks like a similar issue persisting with #3455, just to put it on your radar, since you were able to issue this fix

**Pull request closed without merging**
