### PR TITLE
Add s keybinding

### PR DESCRIPTION
**Pull request by Paxxi**
This is one of the keybindings I use quite often and felt was missing

### CODE REVIEW

**Comment by johnfn** [comment]
Hi @Paxxi! I'm currently in the middle of an enormous refactor that I'm looking to get merged in the next couple of days, which has changed how we add new keybindings: https://github.com/VSCodeVim/Vim/pull/234 

If you can find time, try to add it there. Or I will eventually add it in myself.

Thanks!

**Comment by Paxxi** [comment]
I'll add it there instead, planning on more work time permitting so no problems.  Really want to get some feature parity with the vim bindings for atom so I can make the switch

**Comment by Paxxi** [comment]
Should be updated against current master now and tests are passing

Accidentaly messed up a merge so the rurnning travis build may be broken but it's fixed now.

**Comment by johnfn** [comment]
Great! Thanks a bunch for the contribution! 😄

**Pull request merged**
