### PR TITLE
Ctrl-C should copy to clipboard in visual mode - fix for #1896

### PR DESCRIPTION
**Pull request by philipmat**
When yanking to clipboard, the selection should also reset to normal

### CODE REVIEW

**Comment by philipmat** [comment]
I'll look into the failing tests shortly.

**Comment by Chillee** [comment]
You might already know this (I didn't know this when I first started contributing), but you can run only a select few tests using `newTestOnly`.

If you have any questions about anything, feel free to drop by our slack :)

**Comment by Chillee** [comment]
Ah I've been wondering what that failing test was caused by (which was why I wasn't merging). It's caused by an upstream change (more specifically, this PR: https://github.com/Microsoft/vscode/pull/28238).

I'm fine with merging this and then fixing that upstream change (eventually).

**Comment by philipmat** [comment]
Submitted PR #1926 to fix the tests.
Hopefully, if that passes and gets merged to master before all these other PRs, it should fix them too.

**Comment by ferrao** [comment]
@philipmat Why do you say that `When yanking to clipboard, the selection should also reset to normal`?

All other IDEs that I use to not clear the visual selection mode when I press CTRL-C. 
This behaviour is actually very annoying to me and gets in the way of my workflow.
Is there any option to control this?

**Comment by ferrao** [comment]
@philipmat Just found that `vim.overrideCopy: false` does the trick! I'm happy now!

**Comment by philipmat** [comment]
@ferrao - in Vim itself - i.e. canon, if you select text and yank it (by either `y` or `Ctrl-C`) the mode switches back to Normal from Visual (or Select).

**Comment by ferrao** [comment]
@philipmat Yes, but I am actually on a Mac and  `Cmd-C`/`Cmd-v` does nothing on Vim, allowing me to have two different ways of copying and pasting text around.

With `vim.overrideCopy: true` I loose that.

**Pull request merged**
