### PR TITLE
Fix infinite loop when workspace is empty

### PR DESCRIPTION
**Pull request by frarees**
Repro steps:

1. Open an empty document
2. Use `b`
3. Notice the plugin won't respond to events anymore

### CODE REVIEW

**Comment by frarees** [comment]
Found out that `w` also triggers this issue. Included that fix as well.

**Comment by jpoon** [comment]
Can we add tests? And can you squash your commits?

**Comment by tma-isbx** [comment]
This is also fixed in #160 and contains tests for these conditions.

**Comment by frarees** [comment]
@tma-isbx checked out #160. Looking great!
@jpoon how do we deal with infinite loops in tests? Been playing with Mocha's `timeout` but I'm afraid we cannot gracefully catch an infinite loop happening on tests. Any ideas?

**Comment by jpoon** [comment]
Maybe test the affirmative? Test that the wordLeft does what it should when the workspace is empty?

**Comment by frarees** [comment]
#160 has been merged already so I'm closing this one as fixed.

**Pull request closed without merging**
