### PR TITLE
Undo behavior when position changes using arrows or mouse

### PR DESCRIPTION
**Pull request by xconverge**
This is to address issue #644 

I am not sure I like this approach and want to see if I can do something with cursor ending position vs start position so that it applies to mouse AND arrows without needing to register the keys the way I am.

### CODE REVIEW

**Comment by johnfn** [comment]
This is cool, but be very careful that the arrow keys continue to work for e.g. navigating autocomplete or the quick fix menu.

**Comment by xconverge** [comment]
Yep you are right, I am going to come up with a way to use the cursor position from the last history step instead so that it applies to mouse and arrow keys without changing arrow key behavior, it will be much cleaner

**Comment by xconverge** [comment]
So this is weird but was the best way I could think of solving it easily

this handles mouse and arrow movements without impacting any of the key handlers or anything

it mostly looks for an unexplained/handled jump in position via arrow/mouse/bicycle and says ok that means its time to create a new undo point.

**Comment by johnfn** [comment]
It is a bit weird but not much weirder than a lot of the other fixes we've had to do. So I'm okay with it. :) 

Thanks for the PR @xconverge!

**Pull request merged**
