### PR TITLE
actions wont update desired column by default #4296

### PR DESCRIPTION
**Pull request by schu34**
**What this PR does / why we need it**:
This PR adds the `doesntChangeDesiredColumn` property to `BaseAction` and defaults it's value to `true`. The current behaviour was that after any non-movement action we were updating `vimState.desiredColumn` to be whatever the current position of the cursor is, which usually isn't what we want in most cases. There are a few non-movement actions that _should_ update `desiredColumn` (yanks, and puts) so I've added `doesntChangeDesiredColumn = false` to those.
 
This also fixes the bug below, which was just a symptom of the incorrect behaviour of updating `desiredColumn` on non-movement actions.

**Which issue(s) this PR fixes**
#4296
a bunch of other bugs that haven't been noticed.

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by J-Fields** [comment]
I hate that we have a boolean that starts with "doesnt", but it's better to keep things consistent for now - we can change that later.
This looks good to me, but I'd like to do some manual testing before merging.

**Comment by schu34** [comment]
@J-Fields Any ETA on when this could be merged? Happy to make any tweaks if needed.

**Comment by J-Fields** [comment]
Sorry, I've been busy recently with other things. I'll try to do some testing tonight

**Comment by schu34** [comment]
No problem, totally understand. Just want to make sure it doesn't forgotten completely :)

**Comment by J-Fields** [comment]
Sorry for the delay, @schu34. How confident are you you handled all the commands that should have `doesntChangeDesiredColumn = true`? Also, would you mind writing a test case for the case you described in #4296?

**Comment by schu34** [comment]
@J-Fields I'm fairly confident confident that the case where `doesntChangeDesiredColumn = true` is handled correctly, I'm less confident that I've found every place where it should be `false`. I'm not certain of the functionality of real vim so I just added `doesntChangeDesiredColumn = false` everywhere that was causing tests to fail. 

I'll try and get a test written for this this week

**Comment by schu34** [comment]
@J-Fields added tests, but I've been playing around with this a bit more today and I've found a few bugs related to updating `desiredColumn` when switching back to normal mode from insert mode. going to try and look into it and add a few tests before I go back to work next week.

**Comment by J-Fields** [comment]
Thanks @schu34, I appreciate that. Let me know if there's anything I can do to help you out.

**Comment by schu34** [comment]
@J-Fields the more I played around with this the more weird bugs I found. I opened #4424 which takes mostly the same approach, but defaults all actions to updating `desiredColumn` and just explicitly sets `zz` not to.

I kept this one open in case you or anyone else wants to take a look but feel free to close it if you prefer the other approach.

**Pull request closed without merging**
