### PR TITLE
Fix remaps when entering chinese input mode (composition state)

### LINKED ISSUE #4815: I map ['j', 'k']  to ['esc']. But every time I use Chinese input mode, there will be a bug.
**Describe the bug**
I have mapped ['j', 'k']  to ['esc']. But when I entered `ji` and  `ke` (a word in Chinese)in insert mode, VScode Vim suddenly changed from insert mode to normal mode under the Chinese input method. [Gif](https://img-blog.csdnimg.cn/20200411193412727.gif)

**To Reproduce**

1.  In insert mode, I want to type Chinese words, so I use Chinese input method.
2. But when type `ji`, `Space` and `ke`, the Vim changes to normal mode, which is so weird!

**Expected behavior**
I don't want to trigger the `jk` command in Chinese Input Mode. I just want trigger `jk` when I use ABC Input Mode.

**Environment (please complete the following information):**

- Operating system : macOS Majave Version 10.14.5
- Chrome : Version 80.0.3987.132
- VScode:  Version 1.43.1

### LINKED ISSUE #5237: Mapping error
The first button of mapping, for example, my mapped ESC starts from JJ, but every time I use JJ, the cursor of the first j will move forward one bit, which is a bit troublesome in HTML

### PR DESCRIPTION
**Pull request by berknam**
**What this PR does / why we need it**:
When entering composition state to enter Chinese characters we now don't send the characters to Vim even in insert mode, we only send them after composition end. This should also allow to use Chinese characters in remaps on insert mode.

**Which issue(s) this PR fixes**
fixes #4815 
fixes #5237 

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by cj0687** [comment]
I tested it. It's all right

**Comment by caidwang** [comment]
> I tested it. It's all right

Sorry but I wonder that How I can test it, should I clone the repository, checkout this pr and compile the ts project to generate a new plugin, then put it to the vscode?

**Comment by cj0687** [comment]
> > I tested it. It's all right
> 
> Sorry but I wonder that How I can test it, should I clone the repository, checkout this pr and compile the ts project to generate a new plugin, then put it to the vscode?


I directly use GitHub desktop to clone it, then open it with vscode, and then press F5 to test it. It will open a new vscode window. That's how I test it

**Comment by caidwang** [comment]
> > > I tested it. It's all right
> > 
> > 
> > Sorry but I wonder that How I can test it, should I clone the repository, checkout this pr and compile the ts project to generate a new plugin, then put it to the vscode?
> 
> I directly use GitHub desktop to clone it, then open it with vscode, and then press F5 to test it. It will open a new vscode window. That's how I test it

Thx. I’ll try it later

**Comment by caidwang** [comment]
I tested it too. It works

**Comment by fangbinwei** [comment]
It works for me +1 👍

**Comment by J-Fields** [comment]
Thanks @berknam! Also thanks @cj0687 @caidwang and @fangbinwei for testing!

**Pull request merged**
