### PR TITLE
Fix: cW behaves incorrectly when the cursor is at the end of a word

### LINKED ISSUE #7981: `cW` behaves incorrectly when the cursor is at the end of a word
**Describe the bug**
When your cursor is at the end of a word, cW should delete the last character of the word, same as cw. Instead, it deletes the last character *and* the following word.

**To Reproduce**

insert this line in vscode:

> first second third fourth

put your cursor on the last letter of "second"
press cW

**Expected behavior**
the text should now be:
> first secon third fourth

instead it is:
> first secon fourth

**Environment (please complete the following information):**

- Extension (VsCodeVim) version: 1.23.2
- VSCode version: 1.71.2
- OS: fedora 36

### PR DESCRIPTION
**Pull request by wgr45097**
**What this PR does / why we need it**:
Fix incorrect behavior of `cW` when the cursor is at the end of a word

**Which issue(s) this PR fixes**
fixes #7981 

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by J-Fields** [comment]
Could you please add a test case or two?

**Comment by wgr45097** [comment]
Sure, I have added the test case from #7981 . This is my first time contributing code, so please help me if I do anything in the wrong way.

**Comment by J-Fields** [comment]
Could you also add an identical test for `dW` at the end of a word? That should behave slightly differently (includes the whitespace between words)

**Review by J-Fields — APPROVED** [review]
Much appreciated! Approved pending green tests

**Pull request merged**
