### PR TITLE
Add silent option to key remappings

### PR DESCRIPTION
**Pull request by mly32**
**What this PR does / why we need it**:

Adds a silent option to `IKeyRemapping`. 

**Which issue(s) this PR fixes**

This is related to [https://github.com/VSCodeVim/Vim/issues/5858](https://github.com/VSCodeVim/Vim/issues/5858). This change uses keybindings defined in `settings.json` rather than the remaps talked about in the issue.

**Special notes for your reviewer**:

I am still new to the code base so I had a hard time understanding the testing files. I'm assuming tests for this PR will go into either `remapper.test.ts` or `remaps.test.ts`, but I'm not sure how to write the tests. I'm assuming I'd need to compare step results? I'd like some help in getting one test written.

Currently, I'm manually running the extension and verifying the behavior with these settings:

```jsonc
  "vim.insertModeKeyBindingsNonRecursive": [
    // status bar text should go from "-- INSERT --" to "-- NORMAL --"
    // if silent is false, will go to "leaveSnippet"
    { "before": ["<Esc>"], "commands": ["leaveSnippet"], "after": ["<Esc>"], "silent": true }
  ],
  "vim.normalModeKeyBindingsNonRecursive": [
    // both should go from "-- NORMAL --" to "lineBreakInsert"
    { "before": ["K"], "commands": ["lineBreakInsert"] },
    { "before": ["J"], "commands": ["lineBreakInsert"], "silent": false }
  ],
```

Todo:

After testing behavior is confirmed, the README needs to be updated. Are there other places that also need to be updated?

Notes:

When I tried using VSCode's debugging to run `Build, Run Extension`, I got the error message `Could not find the task 'gulp: build-dev'`. Is this expected? To go around this, I ran `yarn build`, then switched the debugging task to just `Run Extension`.

The `.vscode/extensions.json` file still recommends TSLint but TSLint is deprecated. Is this project going to migrate to ESLint?

In addition to `silent`, I also wanted to update the current boolean setting `showmodename` to some kind of enum which supports options like `always, normal, never`. Where `normal` and `never` behave like the current `showmodename` and `always` would change `StatusBar.setText` to prepend the text of `statusBarText(vimState)` to the result, essentially always showing the vim mode. 

The problem is that this change would break people's configs so I'd like some thoughts.

### CODE REVIEW

**Comment by mly32** [comment]
Any updates on this?

**Comment by mly32** [comment]
@J-Fields, I know you're busy, but are there any updates on this?

**Comment by J-Fields** [comment]
> I am still new to the code base so I had a hard time understanding the testing files

Meh, don't worry about a test case for now (if you could just put a TODO in one of the files you mentioned, that'd be awesome)

> After testing behavior is confirmed, the README needs to be updated. Are there other places that also need to be updated?

Not that I can think of off the top of my head

> When I tried using VSCode's debugging to run Build, Run Extension, I got the error message Could not find the task 'gulp: build-dev'. Is this expected? To go around this, I ran yarn build, then switched the debugging task to just Run Extension.

Not expected (I always do `gulp build-dev` then `Run Extension`, so I hadn't noticed)

> The .vscode/extensions.json file still recommends TSLint but TSLint is deprecated. Is this project going to migrate to ESLint?

#4483

> In addition to silent, I also wanted to update the current boolean setting showmodename to some kind of enum which supports options like always, normal, never. Where normal and never behave like the current showmodename and always would change StatusBar.setText to prepend the text of statusBarText(vimState) to the result, essentially always showing the vim mode.

👍🏻 

> The problem is that this change would break people's configs

We should be able to use a shim (see `overlapSetting`). The setting needs to be migrated anyway (#5851).

**Review by J-Fields — CHANGES_REQUESTED** [review]
Just a TODO for a test to be written in the future and something in the README and this should be good to go. Thanks!

**Comment by mly32** [comment]
Thanks for the feedback. The README has been updated.

My school semester just started so I don't think I can implement `show-mode` anytime soon.

Is the task already marked anywhere as a todo? or should I create an issue and mark it as an enhancement?

**Comment by mly32** [comment]
@J-Fields, are there other changes that need to be added?

**Comment by J-Fields** [comment]
> Is the task already marked anywhere as a todo? or should I create an issue and mark it as an enhancement?

If you could make an issue for it, that would be great

**Review by J-Fields — APPROVED** [review]
Thank you!

**Pull request merged**
