### PR TITLE
Change "when" for ctrl+p key bind in package.json

### PR DESCRIPTION
**Pull request by grosssoftware**
**What this PR does / why we need it**:
Fixes when the ctrl+p key bind is used to enable those who want to remap it. Changing from suggestWidgetAvailable to editorTextFocus allows the key bind to work in either mode. With this change, ctrl+p will work the same as ctrl+n which was fixed some time ago.

**Which issue(s) this PR fixes**
None

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by grosssoftware** [comment]
This has been open for almost a year. Any chance this can be merged?

**Comment by J-Fields** [comment]
Sorry this slipped through the cracks; thanks!

**Comment by tamird** [comment]
This broke the ability to open files with ctrl-p? Seems reminiscent of https://github.com/VSCodeVim/Vim/issues/4017.

**Comment by bradengc-github** [comment]
> This broke the ability to open files with ctrl-p? Seems reminiscent of #4017.

I was able to work around this by adding an entry for <C-p> in `vim.handleKeys' in my user settings. e.g.:

image

**Comment by kendallroth** [comment]
I had to do the same thing with `<C-n>` to allow it to open new files, instead of simply moving cursor down a line 🤷

**Comment by HengHuH** [comment]
> > This broke the ability to open files with ctrl-p? Seems reminiscent of #4017.
> 
> I was able to work around this by adding an entry for in `vim.handleKeys' in my user settings. e.g.:
> 
> image

It is make vim action 'navigation previous in pop-up menu' disable.

**Pull request merged**
