### PR TITLE
No need for "i" flag on a numerical only regex

### PR DESCRIPTION
**Pull request by stefanoio**
Yay! We love PRs! 🎊

Please include a description of your change and ensure:

- [√] Commit message has a short title & issue references
- [√] Each commit does a logical chunk of work.
- [√] It builds and tests pass (e.g `gulp`)

More info can be found on our [contribution guide](https://github.com/VSCodeVim/Vim/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by rebornix** [comment]
@stefanoio nice catch!

**Comment by xconverge** [comment]
@stefanoio Thanks! Did you test this out a little bit? Did it meet your needs?

**Comment by stefanoio** [comment]
@xconverge sorry for the delay, right now it works great, there's still a really minor glitch i can explain with a simple example:
`margin: 1em 2em;`, when the cursor is positioned after the `1` and before the `2` the number affected by the C-a or C-x should be the `2` (it should be always the number underneath the cursor or the next one on the same line), but it's the `1` instead on VSCodeVim v0.4.1.
Should I report it somewhere else? Thank you!

**Comment by xconverge** [comment]
hmm can you file an issue for this? It is a tough one

I am not sure how to fix this immediately while also keeping hex and octal support...

**Comment by stefanoio** [comment]
Sure. Anyway it's just a minor glitch, not really critical IMHO. Thank you!

**Pull request merged**
