### PR TITLE
Support for copy and p command

### PR DESCRIPTION
**Pull request by petegleeson**
Hello, I have added two things:

1. Support for copying to the system clipboard
2. A basic version of the put command that pastes from the system clipboard

When first looking around I found [this issue](https://github.com/Microsoft/vscode/issues/217) on the vscode repository about supporting copy/paste operations for extensions. I have followed the advice in that issue and included the [copy-paste](https://www.npmjs.com/package/copy-paste) npm package to do  copy/paste.

Be great to hear what everyone thinks 👍

### CODE REVIEW

**Comment by petegleeson** [comment]
The build stage seems to be fixed but there is still a problem with some of the unit tests falling over. The error `/bin/sh: 1: xclip: not found` indicates that the linux copy command isn't there. Could be that the docker image doesn't have this installed. Can we apt-get install xclip in the dockerfile? Smells problematic if linux doesn't come with xclip installed by default.

**Comment by edthedev** [comment]
I was able to craft an update to the Travis CI config that fixes the problem.
https://travis-ci.org/edthedev/Vim/builds/126945589

**Comment by jpoon** [comment]
@petegleeson , is there a way in which you can merge @edthedev change (https://github.com/VSCodeVim/Vim/pull/211) into your own PR?

**Comment by edthedev** [comment]
My initial fork was from this branch, so unless I'm mistaken, @petegleeson's commits are included.

I intended to make my pull request back to his copy for #209, but I could not figure out how. I think I pressed the fork button one too many times in the GitHub web interface.

**Comment by edthedev** [comment]
I'll be happy to submit a corrected pull if someone can direct me how. Couldn't find the thing when U tried, but it was kind late. I might have missed something obvious.

**Comment by edthedev** [comment]
Huh. @peteglessons commits are not part of #211. I think I can merge, then submit a new pull.

**Comment by edthedev** [comment]
I did some comparison and found that @petegleeson's solution to the travis.yml file was superior to mine anyway. I have closed #211 as it adds nothing that is not already here.

**Comment by edthedev** [comment]
Latest commit on this branch passes in Travis for me.
https://travis-ci.org/edthedev/Vim/builds/127404327

**Comment by petegleeson** [comment]
Well the travis builds has gone green without any code changes... @edthedev with the magic touch. If you guys are happy with these changes I would love to get this merged 😄

**Comment by edthedev** [comment]
Looks good. 

I closed #212 as duplicate. I'm not sure if Travis CI getting happy is related to poking it again, or if the timing is just coincidence. 

Either way, I'm glad that Travis CI agrees that this looks good to go, though. :)

**Comment by jpoon** [comment]
@petegleeson, @edthedev: Thanks guys. Also pushed out a new release.

**Comment by jpoon** [comment]
Weird, the master branch builds are now broken :|

**Comment by edthedev** [comment]
Changing sudo: false to sudo: true in .travis.yml will probably did the problem. I'm guessing Travis CI changes their rules based on usage frequency thus the tests fail on the main repo after passing in the micro forks.

**Comment by edthedev** [comment]
I would fork and test my theory, except that I will probably continue to get a passing build in my fork, anyway.

If I can find anything in the Travis docs that could shed done light, I'll report that info back here.

**Pull request merged**
