### PR TITLE
Substitute with no range or marks

### LINKED ISSUE #512: Support :s/foo/bar/g style substitutions when text is selected
* VSCode Version: 1.3.1
* VsCodeVim Version: 0.1.3
* OS: Ubuntu 16.04

### PR DESCRIPTION
**Pull request by rebornix**
- [x] Commit message has a short title & issue references
- [x] Each commit does a logical chunk of work.  
- [x] It builds and tests pass (e.g `gulp tslint`)

Fix #512. 

We support followings substitute commands

- [x] `:s/old/new/flags`
- [x] `'<,'>s/old/new/flags`

### CODE REVIEW

**Comment by johnfn** [comment]
The way that it works in vim is if you have a selection, Vim automatically inserts `'<,'>`, which means "run this ex command on a selection." However, you can backspace that and run an ex command not on a selection, if you made a mistake.

Would it be possible to insert those characters into the ex command line in vscode only if there's a selection, then check for them (rather than the existence of a selection) to see if the ex command operates on a selection or not?

**Comment by rebornix** [comment]
@johnfn yeah, I didn't implement `<>` in the first beginning. Let me bring it in.

**Comment by rebornix** [comment]
Support subsitution with no range or marks (now we only support `'<` and `'>`).

**Comment by johnfn** [comment]
@rebornix is this done? sorry, i think i missed your previous message!

**Comment by rebornix** [comment]
yup, it contains everything in description.

**Pull request merged**
