### PR TITLE
Add unit test for long user configured chords.

### PR DESCRIPTION
**Pull request by regiontog**
**What this PR does / why we need it**:
Unit test replicating #2735 
**Which issue(s) this PR fixes**

**Special notes for your reviewer**:
I don't understand the state here well enough to say if it's ok to return from ```handleKeyEventHelper``` like in f88f988f2e9b4bb6e697b6fd0395d0b5198ee7de. However I think the cause of the bug is when the ```NoPossibleMatch``` action is returned from ```Actions.getRelevantAction``` and there is a possible remap. In this case the ```NoPossibleMatch``` action is ran, causing ```recordedState.actionKeys``` to be set to ```[]```

### CODE REVIEW

**Comment by jpoon** [comment]
Hm, I don't quite recall the reasoning behind that piece of code. Your logic does seem to make sense though.

**Comment by regiontog** [comment]
@jpoon I guess the main assumption I'm making here is that a potential remap should alter the state in the same way a ```KeypressState.WaitingOnKeys``` action would. Is that correct or would a remap need to change the state in some additional way?

**Comment by xconverge** [comment]
I don't recall the reasoning here either...

**Comment by jpoon** [comment]
Sorry @regiontog this has taken so long. My hesitation is that I don't recall the reasoning why we had that in the first place, but your PR makes sense so I'm inclined to merge it. What's your take @xconverge?

**Comment by regiontog** [comment]
@jpoon No problem at all, I only run into this problem when making weird keybinds for convenience functions. It seems odd to me that the extension works as well as it does if my reasoning is correct though, so I am cautious of this change as well. I don't know how many UT you guys have for user keybinds, but perhaps it would be good to have some more to increase confidence?

**Comment by xconverge** [comment]
I am ok to merge it and move on :) I can't really recall either way

**Comment by jpoon** [comment]
Yikes, that merge was a mess. Hope that resolves it.

**Pull request merged**
