### PR TITLE
fixes #617

### LINKED ISSUE #617: Left over 'j' when using '.' to repeat a command
Please *thumbs-up* 👍 this issue if it personally affects you! You can do this by clicking on the emoji-face on the top right of this post. Issues with more thumbs-up will be prioritized.

-----

### What did you do?
trailingjbug

Put the exact keys you pressed, if relevant.
/nerd
<enter>
cw
need
jk //this is my custom key config for <ESC>
j
b
.
j
b
.
### What did you expect to happen?
'nerd' to be replaced with 'need' 3 times.
### What happened instead?
'nerd' was replaced with 'need' once and with 'needj' twice.
### Technical details:

* VSCode Version: 1.4.0
* VsCodeVim Version: 0.1.7 
* OS: Windows 10
* VSCode Settings file:
```javascript
{
    "vim.insertModeKeyBindings": [
        {
            "before": [ "j", "k"],
            "after": ["<escape>"]
        }
    ],
    "editor.renderIndentGuides": true
    
}
```

### PR DESCRIPTION
**Pull request by xconverge**
Yay! We love PRs! 🎊

Please include a description of your change & check your PR against this list, thanks:

- [X] Commit message has a short title & issue references
- [X] Each commit does a logical chunk of work.  
- [X] It builds and tests pass (e.g `gulp tslint`)

More info can be found by clicking the "guidelines for contributing" link above.

### CODE REVIEW

**Comment by johnfn** [comment]
I'm a little concerned by this fix. Why is this necessary?

**Comment by xconverge** [comment]
When you use a remapped function, like jj for <Esc>, the 1st j is recorded as an actionkey during insert that was pressed, this removes it. At that time, during insert mode, we have no way of saying hmmmm maybe we are about to exit insert mode, we should not record this keypress.

I also tested with jjj replacing <Esc>

**Comment by xconverge** [comment]
@johnfn what do you think? different way of solving this?

**Comment by xconverge** [comment]
@johnfn I remember I looked at this back when you made that comment. How do I continue to scan for remappings if I am not running it where it is?

**Comment by johnfn** [comment]
What do you mean by "continue to scan for remappings"?

**Comment by xconverge** [comment]
remapper.sendKey is used to check whether a remapping is complete or still in progress, so you have to call it every keypress or atleast some "scan for remapping" sort of function.

How would you delay this until the remapping is complete? What is saying the remapping was detected and is complete?

The way it is currently, the remapped code is executed when the last key of the remapping is pressed:

``` 
const remapping = _.find(this._remappings, map => map.before.join("") === slice.join(""));

if (remapping) {
   ...
}
```

The problem is that before the remapping is complete, we are still inserting these keys (for the case where it ISNT a remap, and just happened to type j once in a word. So how else would we address this so that the first j that was typed is not in the history for when you want to replay the last action with . ?

**Comment by rebornix** [comment]
@johnfn any reason for closing this PR or maybe you are working on this part already?

**Comment by johnfn** [comment]
@rebornix someone told me it had been fixed, somehow.

**Pull request closed without merging**
