### PR TITLE
Select in Visual mode when scrolling

### LINKED ISSUE #907: Ctrl+D / Ctrl+U (page down/up) moves selection when in Visual Line mode
* Click *thumbs-up* 👍 on this issue if you want it!
* Click *confused* 😕 on this issue if not having it makes VSCodeVim unusable. 

The VSCodeVim team prioritizes issues based on reaction count. 

--------
### What did you do?

Make sure `vim.useCtrlKeys` setting is set to `true`.
Open a file that has more content than can fit on the screen.
Place cursor on the first line.
Press `Shift+V` to enter visual line mode (bug is present in visual mode as well)
Press `Ctrl+D` for a page down movement
Notice that the selection is now gone or starts in a different place
### What did you expect to happen?

Text selection should still start on the line which user started Visual mode in.
### What happened instead?

Text selection moves to the current cursor location.
### Technical details:
- VSCode Version: 1.6.0
- VsCodeVim Version: 0.3.7
- OS: macOS Sierra

### PR DESCRIPTION
**Pull request by rebornix**
Ref https://github.com/Microsoft/vscode/issues/22147#issuecomment-297820793 and fixes #907 

With next version of Code, we can expand selection while scrolling.

### CODE REVIEW

**Comment by rebornix** [comment]
We don't merge this before Code ships.

**Comment by johnfn** [comment]
Ah, awesome! Thanks for the vscode-side work, @rebornix!

**Comment by mikew** [comment]
Does this mean using the scrollwheel will expand / contract the selection?

**Comment by xconverge** [comment]
Can you bring this one up to date so that it is ready to be merged as well

**Comment by Chillee** [comment]
I think this also fixes #885

**Comment by xconverge** [comment]
@rebornix can you rebase/update this one?

**Comment by Chillee** [comment]
@rebornix You want me to finish this one?

**Comment by rebornix** [comment]
I'll do this, sorry for being late

**Comment by xconverge** [comment]
This doesn't work once you have made it to the start or end of the pane, try to do it a few times and you will see it gets stuck

**Comment by Chillee** [comment]
@xconverge This is due to something on our end. I'm guessing that we're not updating cursor position properly.

**Comment by Chillee** [comment]
Closed in favor of this PR: https://github.com/VSCodeVim/Vim/pull/1859

**Pull request closed without merging**
