### PR TITLE
Stop snippet insertion from going to visual mode

### LINKED ISSUE #5240: Snippet is not working Properly
when i write a for loop using snipet's . when i press TAB key it's auto come to normal mode. 
Screenshot from 2020-09-25 00-05-41

### LINKED ISSUE #5474: Broken jsx autocomplete
**Describe the bug**
When I write component name and press "tab" I expect to write something between opening closing component's jsx tag, but for some reason vim switches to Visual mode. When I write HTML tags vim switches to Insert mode after pressing "tab". Also 1.16.0 worked properly.

**To Reproduce**

1.`"emmet.triggerExpansionOnTab": true,
     "emmet.includeLanguages": {
   "javascript": "javascriptreact"
}`
2.  Open .js file
3.  Write InputField 
4.  Press tab
5.  Try to write something `<InputField>here</InputField>`

**Expected behavior**
Ability to write code at once after pressing tab autocompletion between opening and closing component's jsx tag and switching vim to insert mode. 
**Screenshots**
https://www.screencast.com/t/uyDHht1WmPAY

**Environment (please complete the following information):**

- Extension (VsCodeVim) version: 1.17.1
- VSCode version: 1.50.1
- OS: windows

**Additional context**
For some snippets like 'clo' which is used for "console.log('object', object)" in [ES7 React/Redux/GraphQL/React-Native snippets](https://marketplace.visualstudio.com/items?itemName=dsznajder.es7-react-js-snippets)  also observed switching to Visual mode instead of insert mode.
This issue driving me crazy I'll appreciate for any suggestions or fix.
Thanks

### LINKED ISSUE #5538: Vsode snippets  choice bug
**Describe the bug**

Using vscode snippets . When there are two variables that both have choice, only the first one can be selected with tab .

**To Reproduce**
Customize a snipptes like the following
```
	"testsnippet": {
		"prefix": "test",
		"body": ["console.log(${1|:one,two,three|}); ${2|one,two,three|};${3:test}"],
		"description": "test snippet"
	}
```

Then enter this test code snippet into the file, and then, for the first variable you can select choice, but not for the second. If I turn off the vim plugin, it works correctly.

**Screenshots**

**Environment (please complete the following information):**

- Extension (VsCodeVim) version:**1.17.1**
- VSCode version: **1.50.1**
- OS: **Windows 10 19041.572**

### PR DESCRIPTION
**Pull request by berknam**
**What this PR does / why we need it**:
When in insert mode and inserting a snippet it will no longer change to visual mode, now it stays in "Insert Mode" or "Insert Mode - Multicursor".

**Which issue(s) this PR fixes**
fixes #5240
fixes #5474
fixes #5538 

**Special notes for your reviewer**:
I've also reverted the ModeHandler static logger change, because like I mentioned before that made it so the logger was no longer working.

### CODE REVIEW

**Comment by J-Fields** [comment]
Could you isolate the logger change into a separate PR? I'd like to keep a change like this isolated

**Comment by berknam** [comment]
> 
> 
> Could you isolate the logger change into a separate PR? I'd like to keep a change like this isolated

I removed the logger change from this PR. Do you want to look into the issue with that static loggers not working, or do you want me to just create a PR reverting those changes?

**Comment by J-Fields** [comment]
> I removed the logger change from this PR

Thanks!

> Do you want to look into the issue with that static loggers not working, or do you want me to just create a PR reverting those changes?

I'll look into it (and probably just revert that change assuming the issue isn't obvious)

**Comment by berknam** [comment]
@J-Fields Have you managed to setup a way of creating beta releases?

**Comment by J-Fields** [comment]
@berknam 8f485b1f959c2865a3888515f442f551cec190ae should fix up the logging issue you've been seeing. It should also reliably update as soon as you change the config (no need to open up a new editor or anything). Let me know if you still have problems.

> Have you managed to setup a way of creating beta releases?

No, I want to get that working soon - I attempted at one point and failed 🙂

**Comment by myfoxit** [comment]
Hi, this isn't fixed , using tab inside a snippet causes still the extension to go into visual mode

**Comment by J-Fields** [comment]
@myfoxit There hasn't been a release containing this PR yet. Sorry for the delay; I've been dealing with some issues on the devops side of things.

**Comment by myfoxit** [comment]
@J-Fields Nah, not a problem my mistake , thought it was released. And I just wanted to mention it ... so sorry from my site ..and thanks

**Comment by J-Fields** [comment]
No worries, hopefully we'll have a new version in your hands soon, there have been a lot of good performance & stability changes recently that I'm excited about.

**Pull request merged**
