### PR TITLE
Fix build per microsoft/vscode#75873

### PR DESCRIPTION
**Pull request by octref**
Fix Linux build on Travis. See https://github.com/microsoft/vscode/issues/75873.

### CODE REVIEW

**Comment by jpoon** [comment]
Oh snap, didn't see this PR. Made the same change. Thanks @octref

**Comment by octref** [comment]
@jpoon Your change won't work as multi-line scripts need to have `|`:

```yaml
before_install:
- |
  if...
    ...
  fi
```

**Comment by octref** [comment]
And I have tested, `/usr/bin/Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &` with semicolon in the end would cause a syntax error. Maybe you can use `(/usr/bin/Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &);`.

Before this commit my build failed as well: https://github.com/octref/vscode-test-sample/commit/0787a54a6c5267eefee9a7ee701fd9329007a188

**Comment by jpoon** [comment]
Reverted my commit and will just take yours as soon as this builds.

**Pull request merged**
