### PR TITLE
Easymotion improvements

### PR DESCRIPTION
**Pull request by MaxfieldWalker**
Make easymotion work even better.

## Improvements

- [x] Use vscode theme color for markers
- [x] Support bi-directional motions #1741
- [x] Tweak status bar text

## Fixes

- [x] Fix EASYMOTION MODE text is not rendered on the status bar after switching texteditors

### CODE REVIEW

**Comment by MaxfieldWalker** [comment]
I don't know what color is good for markers' background and foreground.
For now, I used `activityBarBadge.background` and ``activityBarBadge.foreground`.

https://github.com/MaxfieldWalker/Vim/blob/abffbce06dc2f2a16cbfdcaccf1f63f3ff612145/src/actions/plugins/easymotion/easymotion.ts#L213-L229

#### Examples

[Spirited Away Theme](https://marketplace.visualstudio.com/items?itemName=MaxfieldWalker.vscode-color-theme-spirited-away)

image

Solarized Dark Theme

image

**Comment by Chillee** [comment]
Nice! That looks awesome (way better than our current default of red and black...). However, it seems like you've gotten rid of the current method of choosing colors. Would it be possible to only use the background color if the user has not manually chosen his own colors? I am worried that it does limit customizability for those that want it.

We're also having some trouble with Travis. I'll take a look tonight.

**Comment by MaxfieldWalker** [comment]
This is the function to select color. 

https://github.com/MaxfieldWalker/Vim/blob/abffbce06dc2f2a16cbfdcaccf1f63f3ff612145/src/actions/plugins/easymotion/easymotion.ts#L193-L207

`vim.easymotionMarkerBackgroundColor`, `vim.easymotionMarkerBackgroundColor`, `vim.easymotionMarkerBackgroundColor` options are still alive.

This is a customize example with the configuration below.

```json
{
    "vim.easymotionMarkerForegroundColorOneChar": "#000",
    "vim.easymotionMarkerForegroundColorTwoChar": "#000"
}
```
image

**Comment by Chillee** [comment]
@MaxfieldWalker Awesome. So it only uses the theme's settings if those settings aren't manually set?

**Comment by MaxfieldWalker** [comment]
@Chillee Yes, exactly.

**Comment by Chillee** [comment]
Great! I've fixed the Travis issues, so I'll merge this (and some other PR's) and then issue a release tonight!

**Comment by Chillee** [comment]
@MaxfieldWalker Actually, it seems like an easymotion test is failing, so can you check that?

**Pull request merged**
