### PR TITLE
Fix surround alias using shortcut version with space instead of the ones without

### LINKED ISSUE #4965: extra space in Surround
**Describe the bug**

The simulated vim-surround plugin adds extra space for `b`. 

**To Reproduce**

`foo bar` (cursor on a) => (type `ysiwb`) => `foo ( bar )`

According to the document, `b` is the alias for `)` so I'm expecting `foo (bar)`.

**Expected behavior**
The expected result is `foo (bar)`. 

**Environment (please complete the following information):**

- Extension (VsCodeVim) version: 1.14.5
- VSCode version: 1.46.1
- OS: macOS Catalina 10.15.4

EDIT: Sorry for posting it early while I was still editing.

### PR DESCRIPTION
**Pull request by berknam**
**What this PR does / why we need it**:
Fix surround alias using wrong shortcut version
- Shortcut alias were using the version with space but they are supposed
to use the version without space
fixes #4965
- Add 'a' shortcut alias to '>'
- Add tests for alias
- Add some tests for visual and visual line mode (they are not extensive
but should be enough for now) but they are currently being skipped
because of issue #4973

**Which issue(s) this PR fixes**
fixes #4965

**Special notes for your reviewer**:
I've added the alias 'a' to '\>'. I've also added some visual mode tests, they're not very extensive but should be enough for now just to have something. However, those visual tests are currently being skipped because of issue #4973

### CODE REVIEW

**Comment by J-Fields** [comment]
Just made a quick fix to #4973, can you update this accordingly?

**Comment by berknam** [comment]
Done. Also I've made this comment on your commit:
> To fix the test errors I think the best thing to do is not have the 'testConfiguration' have surround enabled by default and then > enable it only on surround tests.
> I had to do this on my plugin refactor. Look [here](https://github.com/berknam/Vim/pull/1/files#diff-e0df06845c1731321fcc4683646037e3) and [here](https://github.com/berknam/Vim/pull/1/files#diff-efd31f886a37854d3a92af292d427897).

I've encounter that issue as well on my plugin refactor. And I fixed it the way mentioned above. If you want I can create a PR for that?

**Comment by J-Fields** [comment]
Thanks for the heads up - just fixed it

**Comment by J-Fields** [comment]
Thanks!

**Pull request merged**
