### PR TITLE
Support bd[!] [N] to close buffers

### PR DESCRIPTION
**Pull request by th-ad**
**What this PR does / why we need it**:
This PR adds support for the command `bdelete` and all derivatives thereof. It supports the bang operator, as well as the buffer number (tab number in VSCode) to be deleted.

For example, the command `bd` would close the current active tab, while the command `bd 3` would close the 3rd tab open in VSCode.

**Which issue(s) this PR fixes**
Addresses issue #3638. 

**Special notes for your reviewer**:
Open to suggestions on how to make this a little bit more extensible.

This PR misses a couple of things that the `bd` command in Vim provides.

1. No ability to close a buffer with a prefixed buffer number, e.g`[N]bd`. I'm actually not sure if this is possible with the current implementation of `cmd_line`

2. No ability to close a buffer by name.

3. No concept of `#` to delete the previous buffer.

### CODE REVIEW

**Comment by J-Fields** [comment]
Hey @th-ad, would you mind resolving the merge conflicts and fixing up the tests so we can get this merged in?

**Comment by th-ad** [comment]
> Hey @th-ad, would you mind resolving the merge conflicts and fixing up the tests so we can get this merged in?
Yes definitely! I'll try and get the tests fixed up tonight.

**Comment by th-ad** [comment]
> Hey @th-ad, would you mind resolving the merge conflicts and fixing up the tests so we can get this merged in?

Yes definitely! I'll try and resolve both tonight 👍

**Comment by J-Fields** [comment]
Sweet, it's much appreciated! 🙂

**Comment by th-ad** [comment]
@J-Fields I worked on it for a bit tonight and was stuck on the test for `:bd [N]`. Everything else should be good though. I'll give it another shot tomorrow 👍

**Comment by J-Fields** [comment]
@th-ad Still intending to finish that last test?

**Comment by th-ad** [comment]
@J-Fields Yes I am, sorry it's taken so long. I've been pretty busy at work. Alternatively, I could remove the broken test and merge what I have now.

If not, is there a slack/discord where I might be able to get some help with the failing test?

**Comment by J-Fields** [comment]
No worries! There's no big rush, the next release will be a pretty big one I think, and likely won't be ready for a few weeks. There is a slack, but it's pretty dead. I can try taking a look at the test once I get some bandwidth

**Comment by th-ad** [comment]
@J-Fields I was able to do some more work on this today and I found an issue with the `workbench.action.openEditorAtIndexN` command. It doesn't throw an error when the index is outside of the range of open editors. For example, if I only have one editor open and execute the command `bd 1000` it deletes the current editor. Ideally, it would throw an error like `E516: No buffers were deleted`.

Also, VSCode doesn't expose an API to access the open editors which makes testing the buffer functionality more challenging.

Both of the above problems only apply to the command `:bd [N]`, with the buffer number argument included. If we forgo the buffer number argument for now, this PR should be good to merge.

I'm happy to do some pairing on this sometime this week or next weekend if you're still looking to get this over the line. Just let me know 👍

**Review by J-Fields — APPROVED** [review]
Pardon the notifications as I fix merge conflicts. I'm gonna skip the failing test and merge this, because I'd much rather have this implemented than fuss around with writing an annoying test for code that isn't likely to change much. Thanks for the work you put into this!

**Pull request merged**
