### PR TITLE
 Add a command is `D` in visual block mode.

### PR DESCRIPTION
**Pull request by Kooooya**
Yay! We love PRs! 🎊

I add a command is `D` in visual block mode.

It's like below ↓

- [x] Commit message has a short title & issue references
- [x] Each commit does a logical chunk of work.
- [x] It builds and tests pass (e.g `gulp`)

More info can be found on our [contribution guide](https://github.com/VSCodeVim/Vim/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by Kooooya** [comment]
How about this??

**Comment by rebornix** [comment]
LGTM. @Kooooya do you mind writing test cases for it, that would be easy.

**Comment by Kooooya** [comment]
Yes! Please tell me a detail about writing tests. @rebornix

**Comment by Kooooya** [comment]
I've just written a test code by https://github.com/VSCodeVim/Vim/pull/957/files#diff-635380ad4f966541a3e3e35a51293887R59 @rebornix 

now, CI is green. But test failed that executed at my local environment. about below ↓

```
  556 passing (2m)

  2 failing



  1) register Can access '*' (clipboard) register:

      Cursor CHARACTER position is wrong.
      + expected - actual

      -134
      +4

      at Suite.suite (test/register/register.test.ts:31:3)


  2) register Can access '+' (clipboard) register:

      Cursor CHARACTER position is wrong.
      + expected - actual

      -134
      +4

      at Suite.suite (test/register/register.test.ts:38:3)
```

Why? and Is this good?

**Comment by xconverge** [comment]
Those tests fail nearly every time for me locally but not on travis.

**Comment by xconverge** [comment]
BTW are you registered for https://hacktoberfest.digitalocean.com/ @Kooooya! You are doing great and we appreciate the help!

**Comment by johnfn** [comment]
Looks good to me. Thanks, @Kooooya! :)

**Pull request merged**
