### PR TITLE
Enable to highlight f key searches by a option

### PR DESCRIPTION
**Pull request by Yuuki77**
**What this PR does / why we need it**:

Often when I'm using f to search for characters in the current line, I'll run into more occurrences of the character than I expected so highlighting each search match would be nice.

Therefore I added an option called `hlsearchF `

**Which issue(s) this PR fixes**
No

**Special notes for your reviewer**:
* When you test it, please `Vim: Sneak Replaces F` to false. Ideally it works with Sneak search.
* This Also, the highlighted characters will be the characters between the beginning and the end of the line, ignoring the current cursor position. This means that the result will be the same as a search from the beginning of the line.
- This changes the kind of behaviour of `f` command. I though this is convenient, but if you disagree, I can start the search from where the current cursor position is  at on the line

This is my first pr to VSCodeVim so If you have any suggestions, please let me know

Aug-01-2020 01-52-59

### CODE REVIEW

**Comment by Yuuki77** [comment]
@J-Fields What do you think about this feature?
I would love to hear your opinion 😄

**Comment by J-Fields** [comment]
I like the concept. Haven't gotten a chance to dig into the specifics of this PR yet, but I think it might duplicate the functionality of #4718?

**Comment by Yuuki77** [comment]
@J-Fields Thanks I did now know there is a pr for Sneak highlighting.
Most users use Sneak highlighting, so that's better!
I am going to close this pr.

**Comment by J-Fields** [comment]
Thanks for the contribution!

**Comment by ronakg** [comment]
I'd love this highlighting for f command. I don't use sneak, maybe there are more users who are not using either sneak or easy-motion?

**Comment by Yuuki77** [comment]
@ronakg @J-Fields 
Thank you for the feedback
I guess This feature would be useful for some users.
What do you think?
I am going to reopen this pr

**Comment by Yuuki77** [comment]
@J-Fields 😄

**Pull request closed without merging**
