### PR TITLE
Potential fix for non latin chars issue

### LINKED ISSUE #5900: When Korean keyboard layout (Hangul) is active, Entering a space does not work properly.
When Korean keyboard layout (Hangul) is active
Entering a space does not work properly.

If I enter a space twice, it works as one space.

When the extension downgraded to version 17.x, works properly.

Please help!

**To Reproduce**

1. Set keyboard layout to Korean.
2. Enter a word, enter a space once, and then enter the word again.
3. You can see that there is no space.

### PR DESCRIPTION
**Pull request by berknam**
**What this PR does / why we need it**:
This issue was introduced with #5271 while fixing another issue with chinese input. The problem is that chinese input creates a popup box that stays open until the user presses `<Esc>` (to cancel), `<space>` (to accept the first suggestion, it doesn't insert any space), `<Enter>`  (to input the actual latin pressed characters instead of chinese characters) or the number of the pretended suggestion (to insert that suggestion). The `CompositionEnd` event is triggered when the popup box closes, so we are storing the composition state until the `CompositionEnd` and then handle the resulting keys one by one.

The problem is that with korean input, there is no popux box, there is a different cursor that shows the changed/replaced characters with each key press and the `CompositionEnd` event is triggered either by `<Esc>` (to cancel), `<space>` (to accept the current character and insert a space), `<Enter>`  (to accept the current character and insert a new line) or when pressing a character key that can't change the existing one (that accepts the current character, ends composition and then starts composition again with the new character).

The `<space>` and `<enter>` is already fixed on master, the problem is when you press a character that can't change the current one so it accepts the current one and starts a new composition. This happens on vscode side straight away and that means that it starts the new composition state way before we have the chance to handle and insert the accepted character, so the new composition will always start where we will insert the character and after we insert the character it doesn't update its position so it stays on top of our character. (this was mentioned on this comment https://github.com/VSCodeVim/Vim/issues/1287#issuecomment-744963840)

To fix this, I'm inserting the first character after 'CompositionStart' with `default:type` and letting the 'ReplacePreviousChar' event work as default while also keeping track of the `composingText`. And when we get 'CompositionEnd' I call `default:replacePreviousChar` to replace the previous char with '' (empty) to effectively remove the previous char and the handle the `composingText` key by key.

It still bugs me a bit, because my fix is basically doing the exact same thing as vscode does (calling the defaults on the `CompositionStart` and `type` (after composition started) events) in order to keep track of the inserted text and then remove that text and handle it through Vim which will end up inserting it again if it is not remapped. This works well and doesn't reintroduce the issue that #5271 fixed. But this introduces a visual cursor flicker that is barely noticeable if the extensionHost isn't busy but can be noticeable if it is busy.

**Current master:**
koreanInputCurrent

**With fix:**
koreanInput

*Notice that on current master the next key composition starts on top of the one that was just inserted but we can't see it until we introduce another one or a space, that might lead to confusion*

I couldn't find another way to fix this, because we need to let vscode insert the character so that the composition cursor moves correctly but we also need to handle the resulting keys in order to check for remaps, or in the case of chinese for actions, since with chinese pressing `<Enter>` results on the initially pressed latin characters.

**Which issue(s) this PR fixes**
fixes #5900 (the issue with `<space>` was already fixed, however the other mentioned issue on the comments wasn't)

**Special notes for your reviewer**:
@J-Fields Do you have any idea for a way that we can create tests for this sort of issues with different keyboard layouts?

### CODE REVIEW

**Comment by jinkyuhan** [comment]
Korean want it

**Comment by J-Fields** [comment]
> @J-Fields Do you have any idea for a way that we can create tests for this sort of issues with different keyboard layouts?

Nope, this is far outside my wheelhouse.

If we get a few people to test this solution out and verify it's an improvement, I'm happy to merge.

**Comment by tbm98** [comment]
Hi. any update for this PR ?

**Comment by J-Fields** [comment]
Gonna merge because this seems to improve matters, and we'll see if someone complains. Thanks @berknam!

**Pull request merged**
