### PR TITLE
[Fix] Don't add beginning newline of linewise put in visual-mode

### PR DESCRIPTION
**Pull request by tyru**
Thanks for great work.
I'm using Vim for primary text editor but I have to use VSCode at work.
But I found this extension is awesome because Vim like keybinding helps me a lot to concentrate :)

# What this PR does / why we need it

In original Vim behavior, `p` command in visual-mode replaces current text.
VSCodeVim also does it but it is slightly different.
Unnecessary newline is inserted before the text when the text is yanked as linewise.

1. Yank current line's text by `yy`
1. Replace current line's text by `Vp`

In original Vim, it does not change the text (the buffer is marked modified, though).
But VSCodeVim inserts a newline before the current line.

# Which issue(s) this PR fixes

No exact issue yet.
But the problem is touched by #1991 comment.

> Note: there are extraneous newlines in the VSCode output, but I believe this is a separate issue

### CODE REVIEW

**Comment by tyru** [comment]
oops, okay, we should fix `p` to see if current mode is linewise,
But `vimState.currentMode` seems `2 (Visual)` not `4 (VisualLine)` when `p` is invoked... who changed that? :(

**Comment by tyru** [comment]
Fixed the problem and I added the test case too.
But I don't know why the test case seems to pass also in the master branch... :(

Btw, is there a way to run only certain suites/tests?

**Comment by tyru** [comment]
> But I don't know why the test case seems to pass also in the master branch... :(

It seems just I forgot to transpile test code... ;)
Everything seems to work fine.

**Comment by Chillee** [comment]
@tyru To only run certain test cases, write `newTestOnly` instead of `newTest`.

**Comment by tyru** [comment]
@Chillee Ah, thanks! it saves a lot of time! 😄

**Comment by tyru** [comment]
Thanks all!

**Pull request merged**
