### PR TITLE
Fix spec for otherModesKeyBindings to match insert

### PR DESCRIPTION
**Pull request by sectioneight**
No existing issue that I can find, happy to open one if that helps.

### CODE REVIEW

**Comment by sectioneight** [comment]
image

**Comment by sectioneight** [comment]
Note: This is my first time editing a VSCode plugin and I don't think I have my node environment set up properly so I haven't actually tested this, but looking at the code the "other" and "insert" shares the same class with only a different config key.

**Comment by sectioneight** [comment]
Ok, I've tested this now, and set up remaps using the array syntax in the development plugin environment.

**Comment by sectioneight** [comment]
I have no idea what to do about the test failures. They seem unrelated to this change.

**Comment by johnfn** [comment]
Thanks for the PR, @sectioneight! Apologies for the broken tests; we're working on it... 😅

**Pull request merged**
