### PR TITLE
Align Screen Line commands with latest Code API

### PR DESCRIPTION
**Pull request by rebornix**
Yay! We love PRs! 🎊

Please include a description of your change & check your PR against this list, thanks:

- [x] Commit message has a short title & issue references
- [x] Each commit does a logical chunk of work.  
- [x] It builds and tests pass (e.g `gulp tslint`)

Apparently we were not using the latest cursor movement related API.

### CODE REVIEW

**Comment by jpoon** [comment]
LGTM.

**Comment by johnfn** [comment]
I kind of missed the boat on this one but can we use string enums rather than bare strings?

**Comment by rebornix** [comment]
@johnfn definitely good suggestion. Will update them later.

**Comment by aminroosta** [comment]
@rebornix Try `Vgkgkgkgkgk` ing and you will see the same issue i ran into in  #708 

I'm convinced that the [cursorMove](https://github.com/Microsoft/vscode/issues/9143) Api is not handling it correctly!

**Pull request merged**
