### PR TITLE
#6639 #6530 Fixes put command in multi-cursor use case

### PR DESCRIPTION
**Pull request by joel1st**
This fixes the issues outlined in #6639 and #6530 (put command not working correctly for multi-cursors)
It also prevents the multi-cursors being automatically removed when hitting 'p'.

It does this by:
* Preventing overwriting the current register in visual mode when there are multi-cursors.
* Only changing modes after the last cursor is processed/completed.
* Only updating the cursor position for the currently iterated cursor.

### CODE REVIEW

**Comment by joel1st** [comment]
@J-Fields is there anything I can do to help get this across the line?

**Comment by J-Fields** [comment]
> @J-Fields is there anything I can do to help get this across the line?

Sorry, no - I just need to put some thought into this and have been busy with other stuff recently

**Comment by joel1st** [comment]
Any chance this can be revisited? Just changed computers and it has bitten me once again haha.

**Review by J-Fields — APPROVED** [review]
Thanks for the PR and for being so patient 😅 

There still are some bugs - overlapping selections are a bit wonky and register isn't set at all with multiple cursors - but this is a big improvement over the obviously broken current implementation.

**Comment by joel1st** [comment]
Thanks @J-Fields , very happy to see this land :) Glad that there weren't any big refactors happen in this section since I initially put up the PR as well haha :)

**Pull request merged**
