### PR TITLE
reduce suggestion

### PR DESCRIPTION
**Pull request by kimitake**
When inputting, the suggestion window is displayed, but sometimes it is unnecessary.

### CODE REVIEW

**Comment by jpoon** [comment]
This still doesn't fix the actual issue. I have filed -- https://github.com/Microsoft/vscode/issues/997 against vscode for this.

**Comment by kimitake** [comment]
Yes, but much better than current one. At least, editor.action.triggerSuggest should be called in "then" method, otherwise any suggest window won't be displayed during inputting (it is displayed when hit backspace).

**Comment by jpoon** [comment]
> At least, editor.action.triggerSuggest should be called in "then" method, otherwise any suggest window won't be displayed during inputting (it is displayed when hit backspace).

If you want to update the PR to only address this, I can merge that.

I am hesitant to take this PR as a whole as it's a hack that only serves as a band-aid fix. I'd like to see VSCode's response to https://github.com/Microsoft/vscode/issues/997 before we decide how to address this issue.

**Comment by kimitake** [comment]
As you said, the best solution is the fix you request above, but if the fix is merged, we will see a lots of suggest window and can't write code easily using the vim plugin...so I also wait for the response Microsoft/vscode#997 and your decision.

**Pull request closed without merging**
