### PR TITLE
linewise change operator

### LINKED ISSUE #4024: Change operator doesn't behave linewise when appropriate
**Describe the bug**
The change operator doesn't behave linewise when using e.g. `cj` or `ck`. It should remove the entire start and end line but parts of those lines still remain

**To Reproduce**
Edit a file like this. Cursor is at ^
```
1 hello there
2 what's up
      ^
3 las;dkfj
```
Press `ck`. The file looks like this:
```
1 hello the|s up
2 las;dkfj
```
**Expected behavior**
The file should look like:
```
1 |
2 las;dkfj
```
**Environment (please complete the following information):**

- Extension (VsCodeVim) version: 1.10.2
- VSCode version: 1.37.1
- OS: Windows 10

### PR DESCRIPTION
**Pull request by JoshuaRichards**
fixes #4024

**What this PR does / why we need it**:
This makes the change operator behave linewise when appropriate. e.g. `cj` and `ck` delete the entire start and end line.
**Which issue(s) this PR fixes**
#4024

### CODE REVIEW

**Comment by J-Fields** [comment]
Thanks for the PR! Can you resolve the CI error? Not sure why that's been causing trouble recently

**Comment by JoshuaRichards** [comment]
Hey, I'll take a look at those failing tests tonight. I'm having a bit of trouble running them on windows. I had 19 failures out of the box - seemingly related to newlines - and the same 19 after my changes

**Comment by JoshuaRichards** [comment]
I can't get these tests working properly on windows. I haven't found a way to force the test vscode to use linux newlines and I'm getting inconsistent fail counts now so I suspect there's some timing issues as well

**Comment by J-Fields** [comment]
Whoops. Sorry, I caused these test failures 🙂

**Comment by J-Fields** [comment]
@JoshuaRichards could you add a few test cases please?

**Pull request merged**
