### PR TITLE
WIP Fixes #754: Adds j,k,o,<Enter>, gg, G, ctrl+d, and ctrl+u commands for navigating inside the file explorer

### LINKED ISSUE #754: Using j,k,l,i to navigate inside explorer list
* Click *thumbs-up* 👍 on this issue if you want it!
* Click *confused* 😕 on this issue if not having it makes VSCodeVim unusable. 

The VSCodeVim team prioritizes issues based on reaction count. 

--------

That's great if I can forget arrow keys when using VIM mode. That feature already have on Sublime & Atom but I can't find it on VSCode with VSCodeVim.

### LINKED ISSUE #1351: Revert file with `:e!`
Please *thumbs-up* 👍 this issue if it personally affects you! You can do this by clicking on the emoji-face on the top right of this post. Issues with more thumbs-up will be prioritized.

-----

### What did you do?

`:e!`

### What did you expect to happen?

Revert file

### What happened instead?

> Unable to open '!'

### Technical details:

* VSCode Version: 1.10.0
* VsCodeVim Version: 0.5.4
* OS: OSX Sierra

### PR DESCRIPTION
**Pull request by Chillee**
I just copied @rebornix 's keybindings into package.json.

Fixes #754 and fixes #1351

### CODE REVIEW

**Comment by Chillee** [comment]
I just wanted to note that these keybindings don't actually seem to work when I run it in debug mode. I'm not sure why.

**Comment by Chillee** [comment]
Oh, I just realized why we can't do this right now ( I think).

**Comment by Chillee** [comment]
Just kidding.

**Comment by Chillee** [comment]
Actuall

**Comment by xconverge** [comment]
does it work? I dont think it does because of duplicate bindings

**Comment by Chillee** [comment]
No it doesn't. My internship's been sucking up a lot of my time so I've had less time to work on vscodevim :(

**Comment by xconverge** [comment]
The problem is we still think we have an active text editor I think, even when we are focused on the list

**Comment by Chillee** [comment]
@xconverge So the problem is this line (I think): https://github.com/VSCodeVim/Vim/blob/master/extension.ts#L355
`    registerCommand(context, keybinding.command, () => handleKeyEvent(`${ bracketedKey }`));
`

It binds all of our commands to `handleKeyEvent` pretty much. I'm not really sure this is the right approach, but I'd need to think more about how to handle it better (if we even can).

For now, we can just check the `keybinding.when` to see whether we should be handling it.

**Comment by Chillee** [comment]
I also removed the duplicate keybindings test. I don't really think there's much benefit to it.

**Pull request merged**
