### PR TITLE
Fake a Block cursor when in Normal mode

### PR DESCRIPTION
**Pull request by markrendle**
Solution for #19 until the Code team provide a better way of styling the cursor.

Slightly hacky solution using textEditor.setDecorations, but it does give a clear visual indicator when you're in Normal mode.

At present you can't set decorations past the end of text on a line, so when the cursor is on an empty line it doesn't show the block.

### CODE REVIEW

**Comment by jpoon** [comment]
Nice! How would this work in Visual mode?

**Comment by markrendle** [comment]
@jpoon This doesn't do anything with Visual Mode, that's a whole other thing which should probably just work with setting actual selections. I don't mind having a go at Visual Mode if you like, seems like this SDK is pretty easy to work with.

**Comment by markrendle** [comment]
Squashed. I can squash now! :grinning:

**Comment by kimitake** [comment]
I opened long file and moved cursor by j or k, but window is not scrolled.
Up/Down allow keys work, mouse wheel and scroll bar are working, too.

In addition, the block area becomes big at tab space.

**Comment by markrendle** [comment]
I'll take a look at the scrolling issue. Not sure how much can be done about the big tab space thing, since I've basically used a hack to simulate the block cursor. Question is, is the big cursor a bigger issue than having no visual indicator that you're in Normal mode?

**Comment by jpoon** [comment]
@markrendle filed a separate issue for the scrolling issue https://github.com/VSCodeVim/Vim/issues/89 and I already have a fix in https://github.com/VSCodeVim/Vim/pull/87

**Comment by jpoon** [comment]
@andersonj has resolved the conflicts and submitted a new PR. Closing this in favor of https://github.com/VSCodeVim/Vim/pull/102

**Pull request closed without merging**
