### PR TITLE
Implement '' and ``.

### LINKED ISSUE #1089: Marks: go to the position before the last jump
Please *thumbs-up* 👍 this issue if it personally affects you! You can do this by clicking on the emoji-face on the top right of this post. Issues with more thumbs-up will be prioritized.

---

I'm opening this issue as per your instructions on the roadmap. Hoping to bump this feature up a bit. 

It might be because I'm a Vim newb who hasn't unlocked the full potential of marks, but I find myself constantly pressing `' '` and nothing happens.

### PR DESCRIPTION
**Pull request by brandonbloom**
Fixes #1089.

Dependency: https://github.com/Microsoft/vscode/pull/33715

### CODE REVIEW

**Comment by brandonbloom** [comment]
This is currently untested, pending acceptance of upstream patch.

**Comment by Chillee** [comment]
@brandonbloom Sorry, what's the difference between `<C-o>` and the actions you've implemented?

**Comment by brandonbloom** [comment]
The difference is what happens f you execute the command twice in a row. Instead of going back, then back again, it goes back, then forward, alternating back and forth. Very useful for comparing things at distinct points the same file quickly: just hit tick or single-quote over and over again to flip back and forth.

**Comment by xconverge** [comment]
Nice job on the two repo attack here! It is pretty cool when your change gets merged into vscode and here and then the next release makes you happier :)

**Comment by Chillee** [comment]
@brandonbloom Awesome! Nice job! Could you add some tests for this feature?

**Comment by brandonbloom** [comment]
Are there any tests for CommandNavigateBack?

**Comment by Chillee** [comment]
Actually, I doubt we need tests for this; it's just a wrapper of the corresponding VSCode command.

**Comment by Chillee** [comment]
Actually, this doesn't seem to work on the current release. I'm guessing it's an issue with the keybindings.

**Comment by brandonbloom** [comment]
Check to see if the "Go Last" command is available in VS Code. My guess is not yet.

**Pull request merged**
