### PR TITLE
Added :only command and corresponding shortcuts

### PR DESCRIPTION
**Pull request by LeonB**
I added the [`:only` command and shortcuts](http://vimdoc.sourceforge.net/htmldoc/windows.html#CTRL-W_CTRL-O) (`<c-w>o`, `<c-w><c-o>`).

### CODE REVIEW

**Comment by Chillee** [comment]
Looks good to me!

**Comment by Chillee** [comment]
@LeonB Don't worry about the failed CI. It has to do with a Typescript update (I think), and I fixed it in another pending PR.

**Comment by LeonB** [comment]
Awesome!

**Comment by Chillee** [comment]
Thanks for the PR!

**Pull request merged**
