### PR TITLE
fixes #7830 :split cannnot open files correctly

### LINKED ISSUE #7830: :split cannnot open files correctly
**Describe the bug**
The :split (also :vsplit, :vsp) command can split the active editor in the right way, but it does not open the specified file. When I attempted to debug it, I found it seems to **be able to get the correct file path** and `vscode.window.showTextDocument(doc);` not to work.

**Expected behavior**
The file would be opened in the splitted editor.

**Screenshots**
image
image

**Environment (please complete the following information):**

- Extension (VsCodeVim) version: 2022/6/29 version
- VSCode version: 1.70.0-insider
- OS: Windows_NT x64 10.0.22000

### PR DESCRIPTION
**Pull request by unlsycn**
**Which issue(s) this PR fixes**
#7830

### CODE REVIEW

**Comment by J-Fields** [comment]
`:split whatever.txt` works on my machine - any idea why this fixes it on yours? I'm not sure what the difference is

**Comment by HumphreyDotSln** [comment]
> `:split whatever.txt` works on my machine - any idea why this fixes it on yours? I'm not sure what the difference is

I have no idea either.. But I can confirm that `vscode.window.showTextDocument(doc);` doesn't work for me even in a reinstalled environment.

**Comment by bmw** [comment]
> `:split whatever.txt` works on my machine - any idea why this fixes it on yours? I'm not sure what the difference is

I'm not sure either but I'm also having this of split not working. I'm happy to provide whatever info would be useful.

**Comment by theuema** [comment]
Same thing for me here too: :sp an :vsp opens the same buffer again in a split or vsplit window instead of a given file path! 

macOS
VSCode Version: 1.80.2 Commit: 2ccd690cbff1569e4a83d7c43d45101f817401dc
Vim Version: v1.25.2

**Comment by J-Fields** [comment]
Superceded by https://github.com/VSCodeVim/Vim/pull/8535, released with 1.26.0

**Pull request closed without merging**
