### PR TITLE
regex match

### PR DESCRIPTION
**Pull request by rebornix**
Use regex to match brackets instead of iterating all characters one by one. Fix performance issues of inserting brackets in a large file.

cc @xconverge @johnfn

### CODE REVIEW

**Comment by johnfn** [comment]
Haha okay this is really interesting. I don't doubt that it's faster, but I have no idea why. A regex would _certainly_ be slower than a handrolled checking function... 

My best guess is that `Position.IterateDocument` was SUPER slow? That's kind of weird though.

**Comment by rebornix** [comment]
@johnfn it's very likely Generators, which might not be optimized enough by V8.

**Comment by rebornix** [comment]
```
		function norm() { 
			for (var i = 0; i < 10000000; i++);
			return 42;
		} 
		function *g() {
			for (var i = 0; i < 10000000; i++) {
				yield i;
			}
		}
		function gen() {
			for(const i of g());
			return 42;
		}
		console.time('normal');
		console.log(norm()); 
		console.timeEnd('normal');
		console.time('generator');
		console.log(gen());
		console.timeEnd('generator');
```

Result

```
generators.html:21 normal: 6.246ms
generators.html:24 generator: 578.637ms
```

**Comment by johnfn** [comment]
Holy smokes. Yeah, that will do it!

**Pull request merged**
