### PR TITLE
gq preserves whitespace between line breaks

### LINKED ISSUE #6569: gq overrides all spaces according to joinspaces, not just at line boundaries
**Describe the bug**

> I don't know if it was due to this patch #5895 or a later one, but I recently found that e.g. `gqq` replaces all whitespace after a `.` with an exact number of spaces (1 or 2), throughout the paragraph. This differs from Vim, which appears to preserve all internal spaces (unless they get turned into a line break), using `joinspaces` only to determine whether a `\n` should be replaced with one space or two spaces.

_Originally posted by @kainino0x in https://github.com/VSCodeVim/Vim/issues/5895#issuecomment-828695384_

**To Reproduce**

1.  Check joinspaces value (doesn't matter which)
2.  Open a buffer, insert
```
Good morning, how are you?  I'm Dr. Worm.
I'm interested
in      things.
```
3.  press `gqip`
4.  Observe either of the following depending on joinspaces value:
```
Good morning, how are you? I'm Dr. Worm. I'm interested in things.
```
```
Good morning, how are you?  I'm Dr.  Worm.  I'm interested in things.
```
Note that the spaces within the lines have all been reset (incorrectly, in the case of `Dr.`).

**Expected behavior**
Vim produces the following results:
```
Good morning, how are you?  I'm Dr. Worm. I'm interested in      things.
```
```
Good morning, how are you?  I'm Dr. Worm.  I'm interested in      things.
```

**Screenshots**
If remapping-related, please attach log output: https://github.com/VSCodeVim/Vim#debugging-remappings.

**Environment (please complete the following information):**

- Issue Type: `Bug`
- Extension Name: `vim`
- Extension Version: `1.20.1`
- OS Version: `Darwin x64 20.3.0`
- VS Code version: `1.55.2`

<details><summary>json</summary>

```json 
{
	"messages": [],
	"activationTimes": {
		"codeLoadingTime": 75,
		"activateCallTime": 1,
		"activateResolvedTime": 0,
		"activationReason": {
			"startup": true,
			"extensionId": {
				"value": "vscodevim.vim",
				"_lower": "vscodevim.vim"
			},
			"activationEvent": "*"
		}
	},
	"runtimeErrors": []
}
```

</details>

**Additional context**
I think this started happening in the last week or so.

### PR DESCRIPTION
**Pull request by edemaine**
**What this PR does / why we need it**:
* Rewrite 'gq' reflow to apply manual spacing (including `joinspaces` option) just when creating whitespace from what were linebreaks.
* Fix precision around `textwidth`. Now exactly fills lines to width `textwidth`, just like Vim. There's a test to verify this. This required modifying previous test outputs.

**Which issue(s) this PR fixes**
Fixes #6569

**Special notes for your reviewer**:
* I'm having trouble running the added tests locally, so I might need to tweak them slightly.

### CODE REVIEW

**Comment by J-Fields** [comment]
> I'm having trouble running the added tests locally, so I might need to tweak them slightly.

If you have docker installed, `gulp test` should work, otherwise `yarn test`. If you give me some more info I may be able to help (or just keep pushing versions to test via CI 🙂)

**Comment by edemaine** [comment]
Thanks for the offer!

I'm on Windows, so Docker is difficult to install (as it needs WSL), but I think I'll go that route for the future. Just need to do a few more reboots. 🙂 

`yarn test` usually works so-so, but a bunch of tests fail, presumably because of my configuration (`.vimrc` and maybe VSCode extensions etc.?).  CI or Docker seems a more reliable approach, and hopefully I can install and switch to Docker for the future.

**Comment by J-Fields** [comment]
> Fix precision around `textwidth`

Does this fix #3509?

> `yarn test` usually works so-so, but a bunch of tests fail, presumably because of my configuration

Ah yeah on windows a handful of tests fail - I think some due to `\r\n` and such. I've been meaning to get around to fixing those up for a while now, but I generally just use `gulp test` so there isn't a huge incentive

**Comment by edemaine** [comment]
> Does this fix #3509?

Yes.  At least, I tested that [this example](https://github.com/VSCodeVim/Vim/issues/3509#issuecomment-486609571) works correctly now.

I didn't modify how tab indentations work, so [this comment](https://github.com/VSCodeVim/Vim/issues/3509#issuecomment-535289821) may still be an issue.  I could look at this if you'd like.

**Comment by sql-koala** [comment]
@edemaine 
I also run tests on windows.
Check `test\index.ts`, line
   ` glob('**/**.test.js', { cwd: testsRoot }, (err, files) => {`
You can modify that to:
`    glob('**/foobar.test.js', { cwd: testsRoot }, (err, files) => {`
depending what you are working on and then run tests via vscode launch. This is a good workaround for me.

**Comment by J-Fields** [comment]
You should also be able to change any given `suite` to `suite.only` or `newTest` to `newTestOnly`. The tests really should all pass on windows though, I'll try to get to that soon 🙂

**Comment by edemaine** [comment]
OK, I fixed the line width computation again (twice actually), and now #3509 should be fully resolved.  I tested the two examples in that thread, and tested all examples that have changed expected output for matching actual Vim.  Tab behavior also seems mostly correct (there was already a test for that).

Tab behavior isn't correct in the case of an input like `<space><tab>`.  This should evaluate to an indent of tabstop, but it currently evalutes to tabstop+1.  I hope this isn't an issue people will run into, but I could fix it with more work, if desired.

**Comment by J-Fields** [comment]
> OK, I fixed the line width computation again (twice actually), and now #3509 should be fully resolved. I tested the two examples in that thread, and tested all examples that have changed expected output for matching actual Vim. Tab behavior also seems mostly correct (there was already a test for that).

Sweet, thanks!

> Tab behavior isn't correct in the case of an input like `<space><tab>`. This should evaluate to an indent of tabstop, but it currently evalutes to tabstop+1. I hope this isn't an issue people will run into, but I could fix it with more work, if desired.

Yeah mixed indentation is niche enough that I don't really care

**Review by J-Fields — APPROVED** [review]
LGTM, thanks!

**Comment by edemaine** [comment]
Thanks for the quick review!

**Pull request merged**
