### PR TITLE
Ctrl+a and Ctrl+x now create undo points correctly and can be repeate…

### LINKED ISSUE #633: Undo behavior with {}[]()<> does not act exactly as it should
@johnfn took a quick stab at this issue in 7ac106d but the behavior does not fully match the way vim works yet.

When writing something where you open and close the brackets then fill in the interior, a new undo point should be created.

ex:
_if(true){
}_

then filling in 

if(true){
    _int i = 0;_
}

an undo point is created in the first step during insert mode, so pressing u once will get back to the first step, and pressing u again will clear it all.

------

Please *thumbs-up* 👍 this issue if it personally affects you! You can do this by clicking on the emoji-face on the top right of this post. Issues with more thumbs-up will be prioritized.

-----

### Technical details:

* VSCode Version: 1.4.0
* VsCodeVim Version: master as of 7ac106d8708a1ad9918102abf0e59dbb0609cb4b
* OS: OSX

### PR DESCRIPTION
**Pull request by xconverge**
Will probably close #633 after this and PR #634 get merged

### CODE REVIEW

**Comment by johnfn** [comment]
The proper way to do this would just be to make them into Commands rather than Movements. Movements do not create undo points, but Commands do.

**Comment by xconverge** [comment]
Hmm ok, I tried changing it to inherit from BaseCommand since that was my first thought, but it was doing something funky somewhere later down the line...I will check again

**Comment by johnfn** [comment]
Ready to go?

**Comment by xconverge** [comment]
good to go

**Comment by johnfn** [comment]
Great! Thanks again, @xconverge!

**Pull request merged**
