### PR TITLE
Fixed insertLineBefore indent behavior

### PR DESCRIPTION
**Pull request by half-potato**
**What this PR does / why we need it**: It fixes a long standing issue with insertLineBefore behavior, which causes the indent behavior to be inconsistent with Vim.

**Which issue(s) this PR fixes**
#7423 
#7107 

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by J-Fields** [comment]
Could you please write a test case or two?

**Comment by half-potato** [comment]
I also fixed the test that wasn't passing.

**Comment by J-Fields** [comment]
CI is now working; looks like there's a lint error

**Comment by J-Fields** [comment]
Thanks a lot!

**Comment by half-potato** [comment]
I fixed a bug that would leave extra whitespace when VS Code added too much whitespace. Should I submit a new pull request?

**Pull request merged**
