### PR TITLE
Spanish keyboard mappings

### LINKED ISSUE #135: I cant write ;
In spanish keyboard not is posible write ; instead visual code whir this extension write <

### PR DESCRIPTION
**Pull request by frarees**
Fixes #135.

### CODE REVIEW

**Comment by imacnu** [comment]
it´s merge in ext install package version?

**Comment by frarees** [comment]
@imacnu no. You can checkout my `es_maps` branch or [download the patch](https://github.com/frarees/Vim/commit/5912119e6de44f908185e3064865f51b0164280b.patch) and apply it yourself. To test extensions I package them using `vsce package` ([here](https://code.visualstudio.com/docs/tools/vscecli)) to generate a `.vsix` file to later load it via `code file.vsix` ([here](https://code.visualstudio.com/docs/editor/setup)).

**Comment by jpoon** [comment]
@frarees, can you fix conflicts? I can merge afterwards.

**Comment by frarees** [comment]
Travis failed. Actually I feel there's something wrong in the build pipepile as sometimes I manage to get some unexpected __can't open file__ errors while tests run. And has nothing to do with this branch, as I managed to get similar issues on `master`. I'll take a further look to see if I find something about this issue.

**Pull request merged**
