### PR TITLE
fix `z O` unfoldRecursively

### PR DESCRIPTION
**Pull request by VincentBel**
Fix a typo. It is `unfold`, not `unFold`.

image

### CODE REVIEW

**Comment by Chillee** [comment]
Nice catch! Thanks for the contribution (the failing tests are due to an upstream change, so don't worry about them).

**Comment by Chillee** [comment]
Ok it's not passing the CI for w.e. reason...

But it definitely looks right to me, so fuck it.

**Comment by VincentBel** [comment]
lol 🤣

**Comment by Chillee** [comment]
@VincentBel Hah it even works now: https://github.com/VSCodeVim/Vim/commits/master

**Comment by VincentBel** [comment]
@Chillee Magic CI.

**Pull request merged**
