### PR TITLE
Only use regex lookbehind where supported

### PR DESCRIPTION
**Pull request by JKillian**
**What this PR does / why we need it**:

Users on older versions of VSCode were hitting bugs because of lookbehinds in the camel case motion regex. This should fix the issue for those users.

**Which issue(s) this PR fixes**

Fixes https://github.com/VSCodeVim/Vim/issues/3522

**Special notes for your reviewer**:
I didn't get to test this myself on an older version of VSCode. But I think it should work?

### CODE REVIEW

**Comment by jshap70** [comment]
This is very similar to what I was testing. Looks fine. Special note that if a user is building vscodevim on an older branch that some test cases will fail, but seems fine to just say that is disallowed.

**Comment by JKillian** [comment]
Closing this since nobody has complained that they can't upgrade VSCode yet. Will keep the branch around for now though in case it becomes necessary

**Comment by CompuIves** [comment]
Hey! We're using VSCodeVIM inside CodeSandbox (https://codesandbox.io/s/new), which runs VSCode and can run VSCode extensions. For our VIM Mode we use VSCodeVIM (thanks for building this!).

This worked great so far, but we found out that lookbehind regexpressions are not supported in Firefox. I can imagine that this is a very unusual request but would you be open to a PR that adds the lookbehind check and disables it if it detects Firefox/Safari?

**Comment by JKillian** [comment]
reopening for consideration since it seems like there are some legit use cases

**Comment by JoeSchr** [comment]
is this working? I'm trying to access code-server via firefox reality and it gives me this error.

would be really cool if I could code in VR and so far this is the only roadblock :(

anyways thanks for building VSCodeVim, it's really fine!

**Comment by shritesh** [comment]
This was removed again in https://github.com/VSCodeVim/Vim/commit/1d273ebb334b3f7fbf381c32a609b911e5402858#diff-4eb584e50b8970dfd9f200f6d934f418

**Comment by DAddYE** [comment]
> This was removed again in [1d273eb#diff-4eb584e50b8970dfd9f200f6d934f418](https://github.com/VSCodeVim/Vim/commit/1d273ebb334b3f7fbf381c32a609b911e5402858#diff-4eb584e50b8970dfd9f200f6d934f418)

I'm using vscode 1.46.1 through code-server on ipad and I'm getting:

```
Activating extension 'vscodevim.vim' failed: Invalid regular expression: invalid group specifier name.
_logMessageInConsole — abstractExtensionService.ts:396
_logOrShowMessage — abstractExtensionService.ts:410
(anonymous function) — mainThreadExtensionService.ts:70
asyncFunctionResume
_invokeHandler — rpcProtocol.ts:387
_receiveRequest — rpcProtocol.ts:303
_receiveOneMessage — rpcProtocol.ts:230
fire — event.ts:587
(anonymous function) — webWorkerExtensionHostStarter.ts:70
console.ts:137
```

**Comment by J-Fields** [comment]
Ah, I hadn't considered us running in the browser when I removed that. I'll fix it momentarily.

**Comment by DAddYE** [comment]
> Ah, I hadn't considered us running in the browser when I removed that. I'll fix it momentarily.

Thanks so much guys!

**Comment by DAddYE** [comment]
> Ah, I hadn't considered us running in the browser when I removed that. I'll fix it momentarily.

Seems is still not working, I tested from master and still has errors with some grouped regex.
I'll try in the next few days to see if I can profile/debug the extension, because currently the inspector isn't super helpful.

**Comment by J-Fields** [comment]
@DAddYE Just created #5072, I'll try to resolve when I have a chance

**Comment by Immortalin** [comment]
@J-Fields any luck?

**Pull request merged**
