### PR TITLE
Upgrade typescript 2.2.1->2.3.2. tslint 3.10.2->2.3.2. Fix errors

### PR DESCRIPTION
**Pull request by jpoon**
Upgrade tslint

### CODE REVIEW

**Comment by johnfn** [comment]
At some point we should do `strict: true` in our tsconfig.json rather than our hastily assembled set of strict properties. 

Also I want to merge this but it's kind of hard with all the other PRs that don't have this merged in currently... hm

**Comment by jpoon** [comment]
Oh, did you want me to back it out then? :)

**Comment by johnfn** [comment]
Ehh, nah. I'm a fan of YDD (yolo-driven development). If anything bad happens we can just let people know, and this is a definite improvement.

**Comment by jpoon** [comment]
Also messed up on the commit message:
tslint: 3.10.2 -> 5.1.0

**Pull request merged**
