### PR TITLE
[Fix] p won't work in linewise visual-mode at the end of document

### PR DESCRIPTION
**Pull request by tyru**
# What this PR does / why we need it

The fix of #2579 was incomplete.
Because it didn't care the line at the end of document.

# Which issue(s) this PR fixes

No

### CODE REVIEW

**Comment by tyru** [comment]
@TravisBuddy I'm just a bot of applying your patch... ;)
However, how do I run prettier in locally?

**Comment by jpoon** [comment]
Yah. I'm not entirely sure what's going on with our build. Hit the same issue with my PR. gulp forceprettier to run prettier.

**Comment by jpoon** [comment]
Fixed the build issues. Merged fixes into your branch. Should work now....

**Comment by tyru** [comment]
Hmm, sorry, this PR has broken the master status.
Will fix it.

**Comment by xconverge** [comment]
No problem, my fault for merging without updating the branch from master and waiting for the check mark to be green!

**Pull request merged**
