### PR TITLE
Makes all tests pass on Windows

### LINKED ISSUE #1914: Tests failing on master on Windows
I'm creating this issue to track these four tests failing on Windows 10 on `master`.
I'll try working on them one at a time.

```
 1) read Can read shell command output:

      AssertionError: Content does not match; Expected=hey. Actual=hey
      + expected - actual

      -hey
      +hey

      at Object.assertEqualLines (C:\dev\vscodevim\Vim\test\testUtils.ts:28:12)
      at Object.<anonymous> (C:\dev\vscodevim\Vim\test\cmd_line\read.test.ts:20:5)
      at Generator.next (<anonymous>)
      at fulfilled (C:\dev\vscodevim\Vim\out\test\cmd_line\read.test.js:4:58)

  2) Basic sort Sort whole file, dsc:

      AssertionError: Line count does not match.
      + expected - actual

      -4
      +3

      at Object.assertEqualLines (C:\dev\vscodevim\Vim\test\testUtils.ts:35:10)
      at Object.<anonymous> (C:\dev\vscodevim\Vim\test\cmd_line\sort.test.ts:47:5)
      at Generator.next (<anonymous>)
      at fulfilled (C:\dev\vscodevim\Vim\out\test\cmd_line\sort.test.js:4:58)

  3) Basic sort Sort range, dsc:

      AssertionError: Line count does not match.
      + expected - actual

      -5
      +4

      at Object.assertEqualLines (C:\dev\vscodevim\Vim\test\testUtils.ts:35:10)
      at Object.<anonymous> (C:\dev\vscodevim\Vim\test\cmd_line\sort.test.ts:87:5)
      at Generator.next (<anonymous>)
      at fulfilled (C:\dev\vscodevim\Vim\out\test\cmd_line\sort.test.js:4:58)


  4) Mode Normal / can search through multiple newlines:

      Cursor LINE position is wrong.
      + expected - actual

      -0
      +1

      at Suite.suite (C:\dev\vscodevim\Vim\test\mode\modeNormal.test.ts:1492:3)
```

- [x] 1) read Can read shell command output - 
  *NOTE*: with neovim enabled the second line is "hey " <- extra space.  
  Without neovim it doesn't get the first empty line
- [x] 2) Basic sort Sort whole file, dsc:
  *NOTE*: with neovim there's a fourth empty line
- [x] 3) Basic sort Sort range, dsc:
  *NOTE*: probably same as 2)
- [x] 4) Mode Normal / can search through multiple newlines:

### PR DESCRIPTION
**Pull request by philipmat**
Fixes #1914 

https://ci.appveyor.com/project/philipmat/vim/build/1.0.10

### CODE REVIEW

**Comment by jpoon** [comment]
1) Can you squash your commits?
2) I restarted Travis in hopes that it was a flukey error.

**Comment by Chillee** [comment]
@jpoon It has something to do with the neovim script I think. I've been busy interning (my evaluation period is coming up!) but somebody mentioned that it could have to do with our ubuntu version?

I think the better thing to do is to switch to the neovim appImage.

**Comment by philipmat** [comment]
@jpoon if you're asking me about squashing, I'd be happy to do it, but I believe GitHub already supports this through [Squash and merge](https://help.github.com/articles/about-pull-request-merges/)

**Comment by Chillee** [comment]
@philipmat Could you try resolving the conflict (which should be just removing test/cmd_line/read.test.ts) and running the tests again?

**Comment by Chillee** [comment]
Huh. I thought github could show you what the conflicts were.

**Comment by philipmat** [comment]
AppVeyor is green as well: https://ci.appveyor.com/project/philipmat/vim/build/1.0.13

**Comment by Chillee** [comment]
@philipmat Did you and @jpoon decide whether we want to re-integrate Appveyor checks?

**Comment by philipmat** [comment]
@jpoon said, and I quote:

> Happy to set it up again [...]

:)

**Comment by Chillee** [comment]
I always thought that it wasn't really necessary because it's electron, but I guess that's not really true, especially with neovim as well as all other sorts of things.

The main thing I'm concerned with Appveyor is tests being even more flaky, as well as increasing test times.

**Comment by philipmat** [comment]
The tests are not mandatory, but it's good to have signals that everything works well across all platforms VSCode runs on.

If you want to ignore a broken AppVeyor build, there's nothing stoppping you. 

Oh, and AppVeyor seems to finish faster than Travis so there's no waiting either 😀

**Comment by Chillee** [comment]
So long as Windows test fail doesn't prevent us from pushing a release, that's good :+1: 

All we need now is to figure out what those conflicts are...

**Comment by philipmat** [comment]
They're not preventing you because you're using the Travis build to push a release (AFAICT)

I currently see no conflicts on this branch. Should I be looking elsewhere?

**Comment by Chillee** [comment]
No it's good now. Before it said that there were conflicts that needed to be resolved without showing any conflicts, so I was confused. Thanks.

**Comment by Chillee** [comment]
Huh. They seem to only show on web, but not on mobile.

http://i.imgur.com/vYUz67N.jpg

**Comment by Chillee** [comment]
I just merged it on mobile...

**Pull request merged**
