### PR TITLE
make surround repeatable with dot

### LINKED ISSUE #1244: surround should be repeatable with .
* Click *thumbs-up* 👍 on this issue if you want it!
* Click *confused* 😕 on this issue if not having it makes VSCodeVim unusable. 

The VSCodeVim team prioritizes issues based on reaction count. 

--------

### What did you do?

`ysw)` then went to another word and pressed `.`

### What did you expect to happen?

The next word should have be surrounded with parentheses

### What happened instead?

Nothing

### Technical details:

* VSCode Version: 1.8.1
* VsCodeVim Version: 0.5.2
* OS: OSX 10.10.5 / Windows 10

### PR DESCRIPTION
**Pull request by xconverge**
A little funky but I don't think its too bad :)

This is to fix #1244

Any suggestions on a better way would be great... @johnfn

### CODE REVIEW

**Comment by johnfn** [comment]
I think there should be a better way. Just hold on to this guy: https://github.com/VSCodeVim/Vim/blob/master/src/mode/modeHandler.ts#L105

and then re-execute with him when the user presses `.`. That should work, right?

**Comment by xconverge** [comment]
No the problem is getting the operators and movement for the range. It needs to be recalculated based on new position

**Comment by xconverge** [comment]
Example: ysaw" we need to redo aw

**Comment by johnfn** [comment]
Ah I see. So you'd have to refactor him to change the Range into a Motion or something. Meh, this is fine if you don't want to do that.

**Comment by xconverge** [comment]
it is SUPER handy to have, that's for sure... I am not sure I know how to do the motion and either way there is some sense of replaying it back, but then atleast the surround object is fully contained

**Pull request merged**
