### PR TITLE
Fixes #1941: Action repetition with Ctrl-[

### LINKED ISSUE #1941: No action repetition when leaving input mode with CTRL-[
* Click *thumbs-up* 👍 on this issue if you want it!
* Click *confused* 😕 on this issue if not having it makes VSCodeVim unusable. 

The VSCodeVim team prioritizes issues based on reaction count. 

--------

**BUG REPORT**

**Environment**:

- **VSCode Version**: 1.14.2 (cb82febafda0c8c199b9201ad274e25d9a76874e)
- **VsCodeVim Version**: 0.9.0
- **OS**: KDE neon (Ubuntu 16.04)

**What happened**:
`80i=<ctrl-[>`
does not input `=` 80 times.
Leaving input-mode with `esc` or `<ctrl-c>` however, triggers the 80x repetition.

**What did you expect to happen**: 
`=` should be input 80 times.

**How to reproduce it**:
Type `80i=<ctrl-[>`

### PR DESCRIPTION
**Pull request by tagniam**
`Ctrl-[` is already defined as a synonym for `Esc` in `CommandEsc`. Removing `CommandCtrlOpenBracket` fixes the action repetition problem. I think it was code leftover from before a refactor.

Fixes #1941

### CODE REVIEW

**Comment by Chillee** [comment]
@tagniam Thanks! I swear I'll fix the Travis issue soon(TM), and then I can merge a bunch of PR's :(

**Comment by Chillee** [comment]
@tagniam Could you add a test covering this case?

Ask if you need any help with doing tests. `newTestOnly` allows you to just run one test when running the tests.

**Comment by tagniam** [comment]
@Chillee Sure! I haven't written any tests with typescript before, is there anything you're looking for in particular?

**Comment by Chillee** [comment]
@tagniam Just take a look at the other tests in the tests folder. I'd probably put it in modeNormal.test.ts

**Comment by Chillee** [comment]
As for what the tests should cover, the test should break before you fixed this issue, and pass after you've fixed the issue.

So, for example,
you start with an empty file, input `5i=<C-[>`, and end with `=====`.

**Comment by tagniam** [comment]
@Chillee Thanks, I'm in the middle of exams right now but I'll get to writing the tests for both my PRs as soon as I can :)

**Comment by Chillee** [comment]
@tagniam Good luck with your exams! I started working on VsCodeVim purely while I was procrastinating on exams :)

**Comment by tagniam** [comment]
@Chillee Well it looks like I need to procrastinate more often then. :) Thanks!

**Comment by tagniam** [comment]
@Chillee done!

**Comment by Chillee** [comment]
Thanks for the contribution!

**Comment by Chillee** [comment]
Thanks! Sorry for taking so long to merge these.

**Pull request merged**
