### PR TITLE
CtrlKeys should not be treated as <character>

### PR DESCRIPTION
**Pull request by rebornix**
Yay! We love PRs! 🎊

Please include a description of your change & check your PR against this list, thanks:

- [x] Commit message has a short title & issue references
- [x] Each commit does a logical chunk of work.  
- [x] It builds and tests pass (e.g `gulp tslint`)

As title.

cc @johnfn @jpoon

### CODE REVIEW

**Comment by johnfn** [comment]
I actually don't understand what the title means. :P Can you explain more?

**Comment by rebornix** [comment]
@johnfn sorry for not describing it carefully. We can specify a key as `<character>` or `<any>`, ideally `<character>` should not contain `<BS>` but it does. This PR is gonna to fix it.

**Comment by johnfn** [comment]
Ahh, I see.

**Comment by johnfn** [comment]
Ergh, this is going to clash really bad with my multi-cursor mode branch (which is actually done now).

**Comment by rebornix** [comment]
@johnfn MultiCursor is the first priority. Once we have that, then we can go through other tiny changes like this one.

**Comment by rebornix** [comment]
Close this one as I need to have the same feature in InsertPreviousText.

**Pull request closed without merging**
