### PR TITLE
Delete matching bracket upon backspace

### PR DESCRIPTION
**Pull request by rufusroflpunch**
#1228 

When in insert mode, if a user is deleting an opening bracket, and a matching closing bracket is immediately after it, also delete the closing bracket. Corresponding test included.

### CODE REVIEW

**Comment by xconverge** [comment]
related #1085 #1084 

At the time it made sense to put this off in hopes that it was part of the vscode api...

**Comment by xconverge** [comment]
and here is the vscode issue

https://github.com/Microsoft/vscode/issues/17490

**Comment by rufusroflpunch** [comment]
I didn't know that. If you still prefer to wait, I won't hem and haw about it.

**Comment by xconverge** [comment]
I will let @johnfn decide, I think it would resolve a few open issues

The problem is without the proper vscode fix, multicursor stuff is tougher I think, do you know if your fix works with multi cursors?

Also, your way is nice!

**Comment by rufusroflpunch** [comment]
Certainly seems to:

multicursor

**Comment by xconverge** [comment]
Is there a way that you can wrap the functionality using the editor option of whether a user has the "editor.autoClosingBrackets": true?

I think that this is great, might be worth adding a comment to the vscode issue to see what the status is or if they have any thoughts

**Comment by rufusroflpunch** [comment]
It now checks for `editor.autoClosingBrackets` setting before deleting closing bracket.

**Comment by xconverge** [comment]
I would also add single and double quotes as well for this behavior. And < is not included in the default vscode behavior

**Comment by rufusroflpunch** [comment]
I added double, single and weird-thing (`) quotes to the behavior and removed angle brackets. I added the quotes to the `PairMatcher.pairings`  object. I was worried about what downstream affects it might have on the text objects associated with quotes, but from my testing I can't see any problems.

**Comment by xconverge** [comment]
regarding weird-thing (back-tick) and <, what I meant was if you disable the vim plugin, and try various ones, only some of them actually auto delete  ```( { [ ' "``` I think are all of them not ``` ` < ```

no big deal, would just leave it as is for now until @johnfn can give input

**Comment by johnfn** [comment]
First of all, thanks for the PR. This is definitely an issue that has been annoying a lot of people for a long time.

Unfortunately, this problem is actually an annoying one. How does it work with stuff like you type in "(blah)" but then backspace blah and the (? We will somehow need to distinguish a ( that was just entered from a ( which was entered a few keystrokes ago. 

The reason that I have held off solving this is that the correct solution to the problem is to perform all text edits and deletes via vscode api, rather than in the manual way that we are currently doing. Sadly, I believe this would require a large refactor to do correctly, so it's probably better to just manually cover these cases for now.

**Comment by rufusroflpunch** [comment]
You're welcome!

In this case @johnfn, it behaves the same if you enter "()" and backspace the "(", as well as "(blah)" and backspace the "(blah". In both cases, it removes the matching bracket. I believed this to be the desired behavior.

**Comment by johnfn** [comment]
Whoops, I never realized that. Alright, this seems good to me then. :)

**Comment by johnfn** [comment]
Oops, I always forget to release my comments. I have some small suggestions for improvement, but we should be fine here for the most part.

**Comment by rufusroflpunch** [comment]
Thanks for suggestions @johnfn. Done.

**Comment by xconverge** [comment]
this also fixes #1241

**Comment by rufusroflpunch** [comment]
@johnfn Is there something I am missing with this?

**Comment by johnfn** [comment]
Nope, it's fine :)

Dunno if I mentioned this, but apologies for any late responses - I am currently on vacation, hopping all around and not really using my laptop all too much.

**Pull request merged**
