### PR TITLE
fix insertion mappings

### PR DESCRIPTION
**Pull request by kyazdani42**
**What this PR does / why we need it**:
There is an issue in insert modes with key mappings not working properly. \
When typing, keymaps are just not recognized.
 \
This PR tries to fix this by resetting the keys buffer on insert mode if the mapping didn't seem to be a potential remap.

However, it seems there are new issues that i encountered. For instance, this mapping:
```
{
  before: ["<C-e>", "<C-e>"],
  after: ["<Esc>"]
}
```
works, but it erases the previous character from the screen, which is a strange behavior i must say.

**Which issue(s) this PR fixes**
#3221 #3530 #4062

**Special notes for your reviewer**:
first time working on an open source project

### CODE REVIEW

**Comment by dimxdim** [comment]
Tried this fix with current vscode.
I confirm this fixes the issue of needing to wait for timeout to expire before <C-x> insert mode mapping would take place.
Minimal settings to reproduce:
```
{
    "vim.insertModeKeyBindingsNonRecursive": [
        {
            "before": [ "<c-x>" ],
            "after": [ "<ESC>"]
        }
    ],
    "vim.debug.loggingLevelForConsole": "debug"
}
```
Type quickly `a` `C-x`, we now exit insert mode correctly, as expected.

**Comment by kyazdani42** [comment]
Hello,
thanks for your feedback.

Indeed, this fix is just enough for simple sequence mappings, this is why it says 'short' in the PR name. I needed more time to think about this before coming up with a proper solution.

And so i did, i might have found an other way that would fix all mapping issues in insert mode, but i'd have to dig in the code more deeply. I will start working on this again when i have some free time.

**Comment by dimxdim** [comment]
Hi. I really look forward to your next patch. It's a pity there are still bugs in basic mappings, which make it harder to customize and prevent people from switching over from vim/nvim. I am too in-between those. I will be using your patch for the time being and report if there are any related issues. Thx again!

**Comment by dimxdim** [comment]
Today I have tested your new fix. I confirm it works and there is no delay required to trigger either single or double <c-something>.

Regarding the issue you describe with `<c-e><c-e>`, I have come across it too when testing. It is not specific to <c-e> and it is not caused by your fix. It is reproducible with the latest vscodevim in the same manner, just by waiting 2 sec before pressing <c-e><c-e> (or another combination `<c-smth><c-smth>`).

Here is what I found. Using this settings.json file (to disable auto-update overwriting the extension, also using this as the to-be-edited file)"
```json
{
    "vim.insertModeKeyBindingsNonRecursive": [
        {
            "before": [ "<c-x>", "<c-x>" ],
            "after": [ "<esc>" ]
        }
    ],
    "vim.debug.loggingLevelForConsole": "debug",
    "update.mode": "manual",
    "update.enableWindowsBackgroundUpdates": false,
    "extensions.autoCheckUpdates": false,
    "extensions.autoUpdate": false
}
```
Go to line before last, move to the end of the line: `Gk$`.
Enter insert by changing inside the last word: `ciw`.
The word `false` has disappeared and we are in insert.
Then (after waiting 2 sec if using the latest non-patched vscodevim): `<c-x><c-x>`
The change will be undone! (bug)
The same behavior is observed if there was a change to the document before entering insert mode.
If the change was bigger, like appending `"test": "test"`, then multiple `I<c-x><c-x>` will result in multiple "undos", in a step-by-step manner, not like vim.

Try re-opening vscode and without modifying the document: `a<c-x><c-x>`. Will successfully exit insert mode without other modifications (probably because there is no history at this point?). But this time the debug logs: 
```[Extension Host] DocumentChange: warn: Something bad happened in removeChange```

Finally, there is another clue the above "successful" exiting is not the same as just `<esc>`: the cursor is moved 1 space to the left from the position is it supposed to be (like end of line).

It seems to me something is messing up current file's vim-specific history or the file's state.

**Comment by kyazdani42** [comment]
thanks again for the feedback, i feel like this should be tested by more people, although mapping keys in insert mode is not that common.

This bug might need to be issued  properly, it's kind of outside the scope of this PR. It might be good to address this soon, and i might just make another PR if i can. 

in the meantime, i'll wait for the maintainers to take a look at this.

**Pull request merged**
