### PR TITLE
Add back missing control-c registration

### PR DESCRIPTION
**Pull request by sectioneight**
Looks like this was accidentally removed in #445

### CODE REVIEW

**Comment by rebornix** [comment]
LGTM. This might happen as Git Diff looks always weird when adding new actions.

**Comment by sectioneight** [comment]
Yea, this is what the diff looks like for that PR:

image

You can see ControlC is now orphaned without a decorator (is that what they're called in TS?)

**Comment by rebornix** [comment]
Yup, that's Decorator and @johnfn said we had some problems with it and that's why we have to put every command in one single file.

image

See image above, if we add a new command starting with `@RegisterAction`, Git will not treat the first line as `add`, instead it will make the `@RegisterAction` after your change as `add`, which is weird to me and sometimes I revert the last line by mistake.

**Comment by jpoon** [comment]
Thanks @sectioneight for the fix

**Pull request merged**
