### PR TITLE
Fix remap bug with '<' and special keys remaps

### PR DESCRIPTION
**Pull request by berknam**
**What this PR does / why we need it**:
Fix remap bug with '<' and special keys remaps
- Fix remaps confusing '<' as potential remap to special keys like '\<C-x\>'
- Add test for this situation
- Prevent showing special keys like '\<C-x\>' with virtual key decoration

**Which issue(s) this PR fixes**
I don't think anyone has reported this yet

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by J-Fields** [comment]
I'm sure this is the cause of #5188

**Comment by berknam** [comment]
Do you have any remap with Ctrl+something, like `<C-e>` in normal mode?

**Comment by berknam** [comment]
I'm also noticing that you reported that even before version 1.17 was out? Were you using the remap overhaul already?

**Comment by J-Fields** [comment]
> Do you have any remap with Ctrl+something, like <C-e> in normal mode?

Yep I've got a few remaps like that

> I'm also noticing that you reported that even before version 1.17 was out? Were you using the remap overhaul already?

Yeah I generally dogfood with master

**Comment by berknam** [comment]
Then yeah it might have been this.

**Review by J-Fields — APPROVED** [review]
Thanks!

**Pull request merged**
