### PR TITLE
Move commandline to status bar to allow history navigation

### LINKED ISSUE #779: Vim Command Line using up and down to navigate command history
* Click *thumbs-up* 👍 on this issue if you want it!
* Click *confused* 😕 on this issue if not having it makes VSCodeVim unusable. 

The VSCodeVim team prioritizes issues based on reaction count. 

--------
When I do something on the vim command line ( e.g ":%s/foo/bar" ) and I want to do it again I have to type it again. In "normal" vim I can just press keyup/down to navigate my command history, when I try this nothing happens.

### PR DESCRIPTION
**Pull request by xconverge**
Fixes #779

This is our most thumbs upped/sad faced issue currently!

I did not do any complex or majestic refactoring. I mostly took what worked well with searching and applied it to the commandline. Works pretty well!

### CODE REVIEW

**Comment by xconverge** [comment]
The only thing I can't figure out is how to successfully use <D-v> to paste append to the text, <C-v> works fine, but we special cased <D-v>

**Comment by xconverge** [comment]
@jpoon can you take a quick pass on this when you get a chance? Functionally everything is great now, but I am open to feedback!

Any thoughts on me removing the showCmdLine command, I don't think anyone will mind that but I could be wrong...

**Comment by jpoon** [comment]
This is awesome. Thanks for doing this.

**Comment by intijk** [comment]
Thanks for the awesome work!

**Comment by ches** [comment]
> Any thoughts on me removing the showCmdLine command, I don't think anyone will mind that but I could be wrong...

I did use it, to enable a mapping that I use _frequently_ in native Vim, `<Enter>` as an alternative to `:` (I find that holding Shift or other modifier keys for extremely common operations considerably increases fatigue/RSI for me, versus "rolling" across, say, `<Enter>q`).

My old config was:

```js
"vim.normalModeKeyBindingsNonRecursive": [
    // <Enter> => \n
    // https://github.com/VSCodeVim/Vim/issues/1895
    {
      "before": ["\n"],
      "commands": [{ "command": "extension.showCmdLine" }]
    }
]
```

I've updated it with `vim.showQuickpickCmdLine` as a workaround, but of course I then don't benefit from the history feature.

**Pull request merged**
