### PR TITLE
fixes #718 A and I have cursor in right position now

### LINKED ISSUE #718: Visual block mode A does not start inserting text at right position
### What did you do?

t|est
test
test

use ctrl+v to enter visual block and select all of the es's. Then press A and type

### What did you expect to happen?

tes111t
tes111t
tes111t

### What happened instead?

test111
test111
test111

Text was appended one character too far to the right in the column

### PR DESCRIPTION
**Pull request by xconverge**
Yay! We love PRs! 🎊

Please include a description of your change & check your PR against this list, thanks:

- [X] Commit message has a short title & issue references
- [X] Each commit does a logical chunk of work.  
- [X] It builds and tests pass (e.g `gulp tslint`)

More info can be found by clicking the "guidelines for contributing" link above.

### CODE REVIEW

**Comment by rebornix** [comment]
LGTM. Maybe add cases to cover this issue?

**Comment by xconverge** [comment]
We dont have a good visual block test area :( will try to add it to a new file

**Comment by rebornix** [comment]
@xconverge I see, then it's Okay to me.

**Comment by xconverge** [comment]
ah you jumped the gun, expect a PR in a few minutes :)

**Pull request merged**
