### PR TITLE
Fixes visual line and visual block weird pasting with newlines

### LINKED ISSUE #1796: Visual block mode copy, paste
--------

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

**Environment**:

- **VSCode Version**:1.12.2
- **VsCodeVim Version**: 0.8.4
- **OS**: osx 10.12.5(16F73)

**What happened**:

Hello.
I think it's bug.
When I use VisualBlock mode(Ctrl+v),
I selected a word(just a word), press *y* and paste this where I want to insert using (p or P).
Then, you can see insert that word with newline.

**What did you expect to happen**: 

When I insert that word, remove whitespace as newline.

**How to reproduce it**:

Always.
Ctrl+v , select a any word, copy that word using y, paste using a key(p or P)
You can see insert whitespace(new line).

### LINKED ISSUE #1911: Copying to clipboard in visual line and block mode does not produce same results as yanking when pasting
* Click *thumbs-up* 👍 on this issue if you want it!
* Click *confused* 😕 on this issue if not having it makes VSCodeVim unusable. 

The VSCodeVim team prioritizes issues based on reaction count. 

--------

**BUG REPORT**:

**Environment**:

- **VSCode Version**: 1.13.1
- **VsCodeVim Version**: 0.9.0
- **OS**: OS X El Capital 10.11.6

**What happened**:
Copying to clipboard with `Cmd-C` in  should produce the same results upon pasting as would yanking to clipboard register.

Take the following text:

    one two three
    one two three

**Bug in Visual Line mode**
Press: `HV<Cmd-C>H"+P`

**What did you expect to happen**: 

The text to change to:

    one two three
    one two three
    one two three

**What happened**:

    one two threeone two three
    one two three

Executing: `HV"+yH"+P` produces the correct results.

**Bug in block mode**:

    one two three
    one two three

Execute: `H<C-v>ej<Cmd-c>H"+P`

**What did you expect to happen**: 

The text to change to:

    oneone two three
    oneone two three

**What happened**:

    one
    one
    one two three
    one two three

Executing: `H<C-v>ej"+yH"+P` produces the correct results.

### LINKED ISSUE #1919: Pasting to replace lines inserts extra empty lines
* Click *thumbs-up* 👍 on this issue if you want it!
* Click *confused* 😕 on this issue if not having it makes VSCodeVim unusable. 

The VSCodeVim team prioritizes issues based on reaction count. 

--------

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

**Environment**:

- **VSCode Version**: 1.14.0
- **VsCodeVim Version**: 0.9.0
- **OS**: MacOS

**What happened**:

- Yank a single line (`yy`)
- Go to another line
- Select line (`V`)
- Paste to replace it (`p`)

The highlighted line was replaced with two - one empty line, one pasted.

**What did you expect to happen**: 

No empty line pasted. (vim's behaviour)

**How to reproduce it**:

On a file with:
```
first line
second line
```
Executing `ggyyjVp` results in:
```
first line

first line
```

### PR DESCRIPTION
**Pull request by xconverge**
- [ ] Fixes #1796 
- [ ] Fixes #1919
- [ ] Fixes #1911
- [x] Tests for each

### CODE REVIEW

**Comment by brunsgaard** [comment]
I am super happy you are working on this... Cant wait for the PR to be merged. Just wanted to reach out and say thanks 👍

**Comment by xconverge** [comment]
Thanks, it helps, ran into some roadblocks so hopefully I can find some time to take another stab

Visual line is pretty essential to the way I use vim so I would love to get these resolved...

**Comment by xconverge** [comment]
closing for now due to inactivity

**Comment by semyon-san** [comment]
This hasn't been fixed.
Do this: Ctrl+v in normal mode, select a section of text then yank it with y (or d).

Then go in the middle of a line somewhere and  paste using p. The yanked text goes to next line instead of same line.

**Comment by xconverge** [comment]
Correct, it was never merged.

**Comment by semyon-san** [comment]
Do your commits fix the issue now?

**Comment by xconverge** [comment]
Definitely not, they were a work in progress and had adverse side effects, sorry!

**Pull request closed without merging**
