### PR TITLE
Provide an InsertMode command to be able to handle Insert key

### PR DESCRIPTION
**Pull request by gibranrosa**
**What this PR does / why we need it**: It addresses partially #1787 by creating an command vim.insertMode that can be mapped to Insert key, and it simply remap to 'i' when not in insert mode.

**Which issue(s) this PR fixes**: #1787

### CODE REVIEW

**Comment by jpoon** [comment]
@gibranrosa thanks for the PR. It's difficult to ascertain the changes you are making to the `package.json`. I think a better approach may be to add a keybinding for insert and handle it as an action.

**Comment by gibranrosa** [comment]
I think the editor has screwed it up the package.json, I have only made what you said hehe, I create an action exported in the package.json, in which it handles as a "i" to enter the Insert mode. The action is vim.insertMode, if you prefer I can restore the package.json and redo.

**Comment by gibranrosa** [comment]
@jpoon , as @xconverge  have said, with the ?w=1 parameter the diff shows correctly. The code of the extension is a bit complicated, so this was the simplest way I've found to implement it. If you think it really not fits well, I will keep in my fork only, until someone makes it another way or I have some time to digg in.

Thanks!

**Comment by jpoon** [comment]
The proposed fix is a bit hacky, the proper way of doing this would be to implement this as an action. From your last message @gibranrosa, it seems like you are abandoning this PR so I'm going to close it.

**Comment by gibranrosa** [comment]
@jpoon I think I see now, it seems the most simple way would be to add a key in the line below, threating the Insert directly as a "i", do you think it would be appropriated? https://github.com/VSCodeVim/Vim/blob/79ec895622e859b1cb683b766d05344bcaf2f549/src/actions/commands/actions.ts#L623

**Comment by gibranrosa** [comment]
@jpoon  Could you only take a look at my suggestion?

**Comment by jpoon** [comment]
Yes. I think that'll be a better pattern

**Pull request closed without merging**
