### PR TITLE
Simplify storage directory to use supplied extension directory

### PR DESCRIPTION
**Pull request by xconverge**
This is pretty ugly, any suggestions would be appreciated...

We do not get the extension context until the extension is activated (and we need this to get the storage folder), yet we construct some stuff at startup (prior to activation), so now there is a weird dependency in order of operations.

### CODE REVIEW

**Comment by J-Fields** [comment]
Fixes #4055

**Comment by xconverge** [comment]
I couldnt kill mkdirp because we need to create the subfolder unfortunately

**Comment by J-Fields** [comment]
https://code.visualstudio.com/api/references/vscode-api#ExtensionContext
> An absolute file path in which the extension can store global state. The directory might not exist on disk and creation is up to the extension. However, the parent directory is guaranteed to be existent.

Isn't it the case we could just use `fs.mktdir` instead, since we only need to create one directory?

**Comment by xconverge** [comment]
Yes I will do that, duh! Thanks

**Comment by J-Fields** [comment]
Users will lose their history files after updating, right? Probably not a big enough deal to bother copying things over the first time, but we should be aware of that

**Comment by xconverge** [comment]
We have done this in the past without any complaints. Not ideal but I imagine it will be ok, we had far more complaints about WHERE we were storing stuff

**Pull request merged**
