### PR TITLE
I think this may fix the build failure.

### PR DESCRIPTION
**Pull request by edthedev**
I noticed that the automated build failed for your pull request at:
https://github.com/VSCodeVim/Vim/pull/208

I believe this tweak to package.json will fix the issue.

Thanks for contributing to this great tool.

### CODE REVIEW

**Comment by jpoon** [comment]
OMG. You da real MVP!

**Comment by jpoon** [comment]
Oops. I think I was a little overzealous with this merge and it seems like you meant to do a PR against a specific branch. Ah well, it's merged to master in any case.

**Comment by edthedev** [comment]
I'll be happy to move it over an re-submit if needed. Just let me know. I'm working on fixing the Travis build, now.

**Comment by jpoon** [comment]
@edthedev it's fine. Its in the master branch now.

**Pull request merged**
