### PR TITLE
More consistent behavior of C-d

### PR DESCRIPTION
**Pull request by artagnon**
**What this PR does / why we need it**: <kbd>C-d</kbd> behavior is inconsistent with vim.use.

### CODE REVIEW

**Comment by stevenguh** [comment]
Why are we removing `ctrl+d` for `listFocus && !inputFocus`?

**Comment by artagnon** [comment]
... because it overrides the default <kbd>C-d</kbd> on macOS which does a delete-character-forward? As far as I can tell, the setting I'm removing makes <kbd>C-d</kbd> jump to the end of the file, which is very annoying.

**Comment by stevenguh** [comment]
> As far as I can tell, the setting I'm removing makes C-d jump to the end of the file, which is very annoying.

The settings you removed only works on a list and non input, I am failed to see how removing that can makes `C-d` not jump to the end of file.

**Comment by artagnon** [comment]
Oops, sorry. Reverted.

**Review by J-Fields — APPROVED** [review]
Thanks!

**Pull request merged**
