### PR TITLE
[WIP] fixes issue needing to press i or a multiple times to switch modes

### PR DESCRIPTION
**Pull request by xconverge**
Yay! We love PRs! 🎊

Please include a description of your change & check your PR against this list, thanks:

- [X] Commit message has a short title & issue references
- [X] Each commit does a logical chunk of work.  
- [X] It builds and tests pass (e.g `gulp tslint`)

More info can be found by clicking the "guidelines for contributing" link above.

### CODE REVIEW

**Comment by jpoon** [comment]
@xconverge Can you share a repo of the bug you are trying to fix?

**Comment by xconverge** [comment]
What do you mean? This was mostly addressing an issue I have been battling for a long time where sometimes after using cmd+c, cmd+v or the mouse in certain ways, when finishing, it takes 3 presses of i or a to enter insert mode.

This specific commit only fixes on case, so I was trying to move the clearing of actionKeys to this.setCurrentModeByName instead.

**Comment by johnfn** [comment]
@jpoon easiest way is to visually select a word, do ctrl-v, and then try to get into insert mode - you have to press i a few times.

I bugged @xconverge about this already, but although this fix appears to work I'd like it to be a bit more general by running every time a mode change happens. An alternative solution would be to simply override ctrl-v with `*p`.

**Comment by xconverge** [comment]
Yea so I moved it to running it every time a mode changes but the tests fail, so I am working on figuring out why they fail and how to address it

**Comment by jpoon** [comment]
Ah, thanks; that's exactly the explanation (ie. repro steps) I was looking for

**Comment by rebornix** [comment]
As the repro steps are intuitive and descriptive, I think we can have a test case to cover it? @xconverge

**Comment by xconverge** [comment]
The problem is I can easily fix that one case (this PR as is for example), but still encounter the issue many times in other ways (that I do not have the exact repro steps for)

**Comment by johnfn** [comment]
Making a test case for this wouldn't be straightforward. The reason it happens is because we don't handle `ctrl-v` in Vim. Once we intercept it (e.g. to make a test for it), the problem will go away.  :P

**Comment by jpoon** [comment]
Closing this PR as there haven't been any movement in the last month. Fee free to re-open the PR and let us know when it's ready for review.

**Pull request closed without merging**
