### PR TITLE
Add support Y in visual mode

### LINKED ISSUE #573: shift-Y support in visual mode
Currently Y does nothing. From the vim docs:

    {Visual}["x]y		Yank the highlighted text [into register x] (for
    			{Visual} see |Visual-mode|).  {not in Vi}

    {Visual}["x]Y		Yank the highlighted lines [into register x] (for
    			{Visual} see |Visual-mode|).  {not in Vi}

So Y yanks lines, while y yanks arbitrary text.

In visual line mode y and Y should be equivalent, so this is probably quite easy there, but I don't know about non-line mode.

### PR DESCRIPTION
**Pull request by shotaAkasaka**
Fixes #573

### CODE REVIEW

**Comment by jpoon** [comment]
Noice! 🎉 .

**Comment by johnfn** [comment]
If you directly extend the YankOperator, then this will act as an operator, meaning it will be able to be combined with motions to do actions (d is an operator because you can do dw, and c is an operator because you can do c$, etc.) 

That's not what you want here. You want to create and execute a new YankOperator, running it across the entire current line.

Make sense? :)

**Comment by shotaAkasaka** [comment]
@johnfn Thanks for yout comment.
I have to create anad execute new YankOperator,like that?

```
@RegisterAction
export class ShiftYankVisualModeOperator extends BaseOperator {
    public keys = ["Y"];
    public modes = [ModeName.Visual];

    public async run(vimState: VimState, start: Position, end: Position): Promise<VimState> {
      // execute 
    }
}
```

**Comment by johnfn** [comment]
I mean something more along the lines of

`new YankOperator().run(vimState, position.getLineStart(), position.getLineEnd())`

(That is untested code...)

**Comment by johnfn** [comment]
There we go. :) 

Thanks for the PR, @shotaAkasaka!

**Pull request merged**
