### PR TITLE
fixes #7670: support `put =`

### LINKED ISSUE #7670: Support `:pu[t] =`
**Describe the bug**
Ex command `put=range(1,5)` fail

**To Reproduce**

1.  `:put=range(1,5)`
2. `E488: Trailing characters`

**Expected behavior**

Generate 5 lines with numbers 1, 2, 3, 4, 5

**Environment (please complete the following information):**

- Extension (VsCodeVim) version: v1.22.2
- VSCode version: 1.66.2
- OS: Linux x64 5.17.0-1
- Neovim: 0.7.0

### PR DESCRIPTION
**Pull request by elazarcoh**
**What this PR does / why we need it**:
Allow expressions in `put` command.
Implemented `range(start, stop, step=1)`.
example:
`:put=range(10,5,-1)`

**Which issue(s) this PR fixes**
fixes #7670

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by elazarcoh** [comment]
This also set up groundwork for #7136

**Comment by J-Fields** [comment]
> This also set up groundwork for https://github.com/VSCodeVim/Vim/issues/7136

I've got a branch I haven't touched for like a year with some decent progress on expression parsing & evaluating. I'll try to get it to a MVP state and push - then we can hook it up to this. Let me know if you'd be interested in working off that branch, also.

**Comment by elazarcoh** [comment]
> > This also set up groundwork for #7136
> 
> I've got a branch I haven't touched for like a year with some decent progress on expression parsing & evaluating. I'll try to get it to a MVP state and push - then we can hook it up to this. Let me know if you'd be interested in working off that branch, also.

I think it would be wise to start off somewhere, your branch might be a good place for it, as I'm sure how it would be best to design the code anyway.

**Comment by J-Fields** [comment]
See #7920

**Comment by elazarcoh** [comment]
> See #7920

This is much more comprehensive. 
What will be a good way for me to contribute for this PR? What is still needed for it to be ready?

**Comment by J-Fields** [comment]
> This is much more comprehensive.

Yeah I got further along than I'd remembered, actually

> What will be a good way for me to contribute for this PR? What is still needed for it to be ready?

I'd like to get some more polish on it before releasing it, but probably not too much more needs to be done before it's merge-worthy. I think sometime this week I'll release `v1.23.3`, then merge #7920. At that point, we can re-group and see what the best path forward is.

We can target #7920, this MR, and #7893 for `1.24.0`. Pretty exciting stuff!

**Comment by J-Fields** [comment]
Thanks @elazarcoh!

**Pull request merged**
