### PR TITLE
Block Cursor

### PR DESCRIPTION
**Pull request by AndersenJ**
It works and passes the tests. It does have some minor performance issues though.

### CODE REVIEW

**Comment by jpoon** [comment]
Re: https://github.com/VSCodeVim/Vim/issues/19

The performance issues concerns me. Any way to make it better?

**Comment by AndersenJ** [comment]
I'm not sure; all I did was merge markrendle's code with the master branch. I don't really know how it works. I guess I could take a closer look, but it might be better to ask him.

**Comment by markrendle** [comment]
What are the minor performance issues? I'm happy to take a look and see if it's fixable.

**Comment by AndersenJ** [comment]
When I scroll many lines at once with j or k, it slows down and lags considerably. I've only tested that on the Linux client though.

**Comment by markrendle** [comment]
I took a look at the Cursor code in VSCode itself (https://github.com/Microsoft/vscode/tree/master/src/vs/editor/browser/viewParts/viewCursors). It doesn't look like a huge job to add in some kind of dynamic styling for the cursor with access through the API. I'll have a proper look at the weekend.

**Comment by jpoon** [comment]
Thanks @markrendle and @AndersenJ. As master changed quite a bit, I decided to create a new PR (https://github.com/VSCodeVim/Vim/pull/120) taking inspiration from your work instead of dealing with the conflicts. 

I didn't see any perf issues.

**Comment by caiocutrim** [comment]
I have the cursor block when scrolling many lines in the code, I get lag. When I tip :19 to go the line 19 the cursor will go to line 20 lol I don't know why this is happening... I've very excited with this project;

**Comment by caiocutrim** [comment]
This is happening when the keys j and k is down....The screen freezes...

**Comment by johnfn** [comment]
Hey @caiocutrim would you mind opening a new issue for those problems? :)

**Pull request closed without merging**
