### PR TITLE
add sentence when currentChar is undefined

### PR DESCRIPTION
**Pull request by monjara**
**What this PR does / why we need it**:
This PR fixed text objects such as iw and aw to behave like vim.

When a textobject such as iw or aw is entered and its position is on an empty line, 
* aw(W) will select to the end of the next word.
* iw(W) will select up to the next word.

**Which issue(s) this PR fixes**
#6418

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by J-Fields** [comment]
Could you please add a few test cases?

**Comment by J-Fields** [comment]
CI is busted right now - I'll try to fix that up later

**Comment by monjara** [comment]
Thank you!

**Comment by J-Fields** [comment]
Thank you!

**Pull request merged**
