### PR TITLE
Make j and k commands fold frinedly!

### PR DESCRIPTION
**Pull request by aminroosta**
Right now fold commands are practically useless, because as soon as you start `jjjjj` or `kkkk` ing over them, they open 😢 

The only possible solution is to use `cursorMove` command (unfortunately) ... and this is not going to change with upcoming api changes 😞 

@johnfn So with this PR i have tried to fix moving around with `j` and `k` keys.

Note, if you try `moveup` and then `movedown` to get the position of previous visible line, it causes `kkkk` ing around slow.

There is also a minor fix for `zc` command which for no good reason puts cursor into visual mode.

@johnfn Let me know if you need me to change something.

### CODE REVIEW

**Comment by aminroosta** [comment]
There is bug with `Vkkkk` ing right now, I will try to fix it.

**Comment by johnfn** [comment]
Ping me when this is good @aminroosta :)

**Comment by aminroosta** [comment]
@johnfn I've given up on this PR.

**Comment by jpoon** [comment]
Closing this PR as there haven't been any movement in the last month. Fee free to re-open the PR and let us know when it's ready for review.

**Comment by avigliotti** [comment]
Any news about fixing this issue?

**Pull request closed without merging**
