### PR TITLE
Wip#389 Marks across files

### PR DESCRIPTION
**Pull request by arussellk**
Here's my progress on global marks. You can give feedback now, or ignore this PR until I finish it further.

I still need to code something to move the global marks if changes are made to that mark's document (and probably remove the mark if that document is closed).

### CODE REVIEW

**Comment by jpoon** [comment]
Closing this PR as there haven't been any movement in the last month.

**Comment by walston** [comment]
The currently open Issue for this is #1692, as #389 was closed in favor of it's more descriptive OP.

**Comment by yebrahim** [comment]
Any chance of bringing this back?

**Comment by leushkin** [comment]
I hope that someone will implement it

**Pull request closed without merging**
