### PR TITLE
fix: only create new file on split when specified

### PR DESCRIPTION
**Pull request by bcho**
**What this PR does / why we need it**:

#8698 introduced support for creating new file on split. However, the create behavior should only be used when there is a file arg specified for the split command.

| command case | behavior |
|-----------|---------|
| `(v)sp` | open new split with existing open file |
| `(v)sp <file>` | open new split with the giving file path, create if needed |

#8698 fixed the 2nd case, while broke the 1st case.

**Which issue(s) this PR fixes**

#8730 

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by bcho** [comment]
I am not sure how to proper add tests for this behavior, will try submit one in the new pr.

**Comment by bcho** [comment]
hi @J-Fields could you please take a look on this? Sorry for the ping, but the bug is quite annoying :(

**Comment by pimpeters** [comment]
Any ETA on when this will be merged?

**Review by pimpeters — APPROVED** [review]

**Comment by J-Fields** [comment]
Thanks!

**Pull request merged**
