### PR TITLE
fix #639 visual block mode minor issues

### LINKED ISSUE #639: Can't enter visual block mode from visual mode, need to be in normal
### What did you do?

Go into visual mode, press ctrl + v to try and enter visual block mode.

Also ctrl + v should EXIT visual block mode

### What did you expect to happen?

Go into visual block

### What happened instead?

Stayed in regular visual mode

### Technical details:

* VSCode Version: 1.4.0
* VsCodeVim Version: 0.1.7
* OS: Win10 64

### PR DESCRIPTION
**Pull request by xconverge**
Yay! We love PRs! 🎊

Please include a description of your change & check your PR against this list, thanks:

- [X] Commit message has a short title & issue references
- [X] Each commit does a logical chunk of work.  
- [X] It builds and tests pass (e.g `gulp tslint`)

More info can be found by clicking the "guidelines for contributing" link above.

### CODE REVIEW

**Comment by johnfn** [comment]
You are on a roll! :)

Tell me when this one is good to go.

**Comment by xconverge** [comment]
It is good to go for now, I will open new issues as I find them

sorry if the tiny little fixes are annoying, I will let you guys focus on bigger things, but they should be quick to review at least

**Comment by rebornix** [comment]
@xconverge these tiny fixes make the project stable and trustworthy. Do appreciate it.

**Comment by johnfn** [comment]
Please, make as many tiny little fixes as your heart desires! 😄

**Pull request merged**
