### PR TITLE
Fixes #1874: Selection not selecting properly for one character.

### LINKED ISSUE #1874: Add next occurrence bug with single character selections (such as ";")
Hey @Chillee, wanted to thank you for your awesome work on visual mode selection and add next occurrence! It works much better now, though there is still one small bug remaining that I noticed (for reference, this bug was happening before the 0.9.0 patch as well, so it's not a new one). 

I hope this is clear, but if not please let me know if I can help to provide any more information!

* Click *thumbs-up* 👍 on this issue if you want it!
* Click *confused* 😕 on this issue if not having it makes VSCodeVim unusable. 

The VSCodeVim team prioritizes issues based on reaction count. 

--------

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): Bug Report

**Environment**: MacOS

- **VSCode Version**: 1.13.1
- **VsCodeVim Version**: 0.9.0
- **OS**: MacOS 10.12.5

**What happened**: When just trying to select end of line semicolons with add next occurrence, the correct selection only lasts for one occurrence. After the second selection, it changes the selection I'm trying to highlight. (It appears to go back one character add this previous character to the search on the second occurrence)

For example, I will select `;` in Visual mode, then hit the keyboard shortcut to add next occurrence. It works properly to select the next line. Then, the third time I issue that command, it changes my selection from `;` to `};` (you can see it also changes in VSCode's search bar at this time). 

Here's a GIF showing this in action (_Note that my Ctrl+G is mapped to Cmd + D (add next occurrence)_)
Semicolons selection match

**What did you expect to happen**: All the proper instances of `;` should be selected one at a time, without changing the search selection to a different value. Only `;` should be matched, not `};` nor should the search value change.

**How to reproduce it**: Have a file with end of line semicolons coming after closing braces. Select the first semicolon (not including the curly brace) and Add Next Occurrence. This only seems to be happening with one character selections. Feel free to use this example:
```
/**
 * @param {number[]} nums
 */
var Solution = function(nums) {
    
}; 

/**
 * Resets the array to its original configuration and return it.
 * @return {number[]}
 */
Solution.prototype.reset = function() {
    
}; 

/**
 * Returns a random shuffling of the array.
 * @return {number[]}
 */
Solution.prototype.shuffle = function() {
    
}; 

/** 
 * Your Solution object will be instantiated and called as such:
 * var obj = Object.create(Solution).createNew(nums); 
 * var param_1 = obj.reset(); 
 * var param_2 = obj.shuffle(); 
 */

Solution.prototype.test = function() {
    
}; 
```

### PR DESCRIPTION
**Pull request by Chillee**

### CODE REVIEW

**Comment by xconverge** [comment]
rebase please

**Comment by Chillee** [comment]
@xconverge haha

**Comment by Chillee** [comment]
Now the massive amounts of work I did to fix this issue will be revealed!

**Comment by xconverge** [comment]
Haha nice!

**Comment by Chillee** [comment]
Oh yeah I forgot. Fixing this issue actually breaks a couple of test cases.

That's because our old cold assumes the current behavior.

**Comment by jpoon** [comment]
As this PR has gone stale, I'm going to close it. Feel free to re-open when ready for review/merge.

**Pull request closed without merging**
