### PR TITLE
Add commands is `s` and `S` in visual block mode.

### PR DESCRIPTION
**Pull request by Kooooya**
Yay! We love PRs! 🎊

Add commands is `s` and `S` in visual block mode.

- [x] Commit message has a short title & issue references
- [x] Each commit does a logical chunk of work.
- [x] It builds and tests pass (e.g `gulp`)

More info can be found on our [contribution guide](https://github.com/VSCodeVim/Vim/blob/master/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by rebornix** [comment]
wow, this PR is amazing @johnfn

**Comment by johnfn** [comment]
It's beautiful!

Only suggestion: make `keys = [["S"], ["s"]]` (which allows either sequence to trigger the action) in the first class, and remove the second class entirely.

**Comment by Kooooya** [comment]
https://github.com/VSCodeVim/Vim/pull/954/files#diff-7addcd1a8a241060a73b1fe4abb39960R3861

I fixed! ok?? @johnfn

**Comment by johnfn** [comment]
Yup! :) Thanks for the PR, @Kooooya!

**Pull request merged**
