### PR TITLE
Handle Ns and fix #684

### LINKED ISSUE #684: Ns don't work
### What did you do?

`|abcde`, press `3s`.

### What did you expect to happen?

`|de` in insert mode.

### What happened instead?

`|bcde` in insert mode.

* VSCode Version: 1.4.0
* VsCodeVim Version: 0.1.7
* OS: OS X 10.11.6

### PR DESCRIPTION
**Pull request by octref**
- [x] Commit message has a short title & issue references
- [x] Each commit does a logical chunk of work.  
- [x] It builds and tests pass (e.g `gulp tslint`)

### CODE REVIEW

**Comment by rebornix** [comment]
@octref do you mind rebasing against master to resolve the conflicts, others are perfect.

**Comment by jpoon** [comment]
And squashing the commits :)

Although, we can squash when we merge.

**Comment by markrendle** [comment]
Pro Tip: I've started using GitKraken to do squashes with a helpful GUI (it's also very good for diff/merge).

**Comment by octref** [comment]
@rebornix @jpoon Done. Thanks for the tips!

@markrendle Thank you, I might look into it if it has good diffs. I'm good on CLI git for now.

**Comment by rebornix** [comment]
The failing test has nothing to do with @octref 's change so close/reopen it to trigger the CI again.

**Comment by jpoon** [comment]
Thanks @octref.

@rebornix, you *should* be able to restart the builds through Travis presuming that Travis inherits the GitHub rights.

**Comment by rebornix** [comment]
@jpoon thanks for the info, don't know yet I have the power to manage Travis 💯 !

**Pull request merged**
