### PR TITLE
Keep cursor position when `gd` opens a new file

### PR DESCRIPTION
**Pull request by grncdr**
This fixes the issue #1171, but is neither elegant nor robust. The tests are spitting out a _lot_ of noise like `invalid value for set cursor position. This is probably bad?` and `Error: Illegal value for line`which makes me quite nervous, but they seem to do this on the master branch as well.

There are also 2 failing tests (edit: these don't seem to fail on Travis 😕 ) , which seem like they _could_ be legitimate failures, but I really can't tell:

```
  2 failing
  1) Motions in Normal Mode Remembers a reverse search from another editor:
      AssertionError: Cursor CHARACTER position is wrong.
      + expected - actual
      -18
      +11

  2) Motions in Normal Mode Shares reverse search history from another editor:
      AssertionError: Cursor CHARACTER position is wrong.
      + expected - actual
      -18
      +11
```

As I understand it, this is meant to test that all editors share the the current search term when using `?`. E.g. `?blah<Enter><C-w><C-w>n` will jump backwards from the current cursor position to the first preceding instance of `blah`.
 
I did some manual testing of this feature locally (doing reverse searches in split editors working on the same file), and couldn't replicate the behaviour of the tests (that is, reverse search seems to work perfectly across editors).

### Checklist

- [x] Commit message has a short title & issue references
- [x] Each commit does a logical chunk of work.
- [x] Also went through https://gist.github.com/rebornix/d21d1cc060c009d4430d3904030bd4c1 for good measure.
- [ ] It builds and tests pass (e.g `gulp`)

### CODE REVIEW

**Comment by johnfn** [comment]
Thanks for the PR. This one has been a thorn in our side for quite some time. I am currently traveling, but I will try to review it when I find some time!

**Comment by grncdr** [comment]
Hm, after merging master the travis build fails, but with only _one_ of the errors I observed locally.

**Comment by johnfn** [comment]
The two reverse search testcase failures were happening on my machine as well. I am not sure why, but those tests do particularly weird things with opening up new IDEs - maybe the API changed or something...

**Comment by grncdr** [comment]
I've been using this day-to-day, and it's not quite right yet. It seems like the vim state cursor is not always accurately updated when switching windows. Will dig into it later.

**Comment by xconverge** [comment]
Great job test driving it for a bit, that's appreciated :)

**Comment by johnfn** [comment]
I finally managed to fix this. I don't blame you for not trying to track down the root cause; it was pretty difficult to find!

**Pull request closed without merging**
