### PR TITLE
Fix for issue #571

### PR DESCRIPTION
**Pull request by xconverge**
Please include a description of your change & check your PR against this list, thanks:

- [x] Commit message has a short title & issue references
- [x] Each commit does a logical chunk of work.  
- [x] It builds and tests pass (e.g `gulp tslint`)

More info can be found by clicking the "guidelines for contributing" link above.

### CODE REVIEW

**Comment by johnfn** [comment]
Awesome work - thanks, @xconverge!

**Comment by jpoon** [comment]
@xconverge FYI, here's a neat trick: you can also seamlessly close the issue with your PR if you include one of these keywords from GH: https://help.github.com/articles/closing-issues-via-commit-messages/

**Comment by xconverge** [comment]
@jpoon cool, will use that for the next one :) 

So If my commit message was "Fixes #571xxx" it would have automatically closed the issue?

**Comment by jpoon** [comment]
Yep! When you initially submit the PR, GH will automatically add a reference to the PR from the issue and when the PR is merged, GH will automatically close the referenced issue.

**Pull request merged**
